=head1 INSTALLING

You can get the B<ufo> application from L<http://github.com/masak/ufo>

In the directory:

  ufo

  make

  make test

If all looks good:

  make install

=head1 INSPIRATION

I have had great success with Stevan Little's Bread::Board in Perl 5, and
thought that this would be a great addition to the Perl 6 module set.

=head1 AUTHOR

Jason May, E<lt>jason.a.may@gmail.comE<gt>

=head1 LICENSE

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut
