=encoding utf8

=for HTML <a href="https://travis-ci.org/zoffixznet/perl6-Acme-GiveUp"><img src="https://travis-ci.org/zoffixznet/perl6-Acme-GiveUp.svg?branch=master"></a>

=head1 NAME

Acme::GiveUp - (╯°□°）╯︵┻━┻  when you just want to give up for the day

=head1 SYNOPSIS

    use Acme::GiveUp;

    ... buggy code that's been annoying you all day...

    (╯°□°）╯︵┻━┻

    # problem solved (shuts down the computer, by default)

=head1 DESCRIPTION

If you're tired and pissed off, it's probably time to take a break! Flip the
table and walk away:

    (╯°□°）╯︵┻━┻

=head1 EXPORTS

This module exports one term: (╯°□°）╯︵┻━┻

Using this term will, by default, run C<shutdown -h now>. You may also
specify a less helpful command to run using the C<@*GIVE-UP-CMD> dynamic
variable:

    @*GIVE-UP-CMD = <killall vim>;

    (╯°□°）╯︵┻━┻

This will kill all C<vim> sessions.

=head1 REPOSITORY

Fork this module on GitHub:
L<https://github.com/zoffixznet/perl6-Acme-GiveUp>

=head1 BUGS

To report bugs or request features, please use
L<https://github.com/zoffixznet/perl6-Acme-GiveUp/issues>

=head1 AUTHOR

Zoffix Znet L<http://zoffix.com/>

=head1 LICENSE

You can use and distribute this module under the terms of
The Artistic License 2.0. See the C<LICENSE> file included in this distribution
for complete details.

=cut

