=begin pod

=head1 Model

Model contains choosen attributes inisde classes and and low level methods to contact game servers like get mentioned attributes or do something. No decisions or logic should be found here.

=head1 Logic

L<doc:LacunaCookbuk::Logic::Ambassador>

P<doc:LacunaCookbuk::Logic::Ambassador>

L<doc:LacunaCookbuk::Logic::BodyBuilder>

P<doc:LacunaCookbuk::Logic::BodyBuilder>

L<doc:LacunaCookbuk::Logic::Chairman>

P<doc:LacunaCookbuk::Logic::Chairman>

L<doc:LacunaCookbuk::Logic::Chairman>

P<doc:LacunaCookbuk::Logic::Commander>

L<doc:LacunaCookbuk::Logic::IntelCritic>

P<doc:LacunaCookbuk::Logic::IntelCritic>

L<doc:LacunaCookbuk::Logic::OreCritic>

P<doc:LacunaCookbuk::Logic::OreCritic>

L<doc:LacunaCookbuk::Logic::PlanMaker>

P<doc:LacunaCookbuk::Logic::PlanMaker>

L<doc:LacunaCookbuk::Logic::Secretary>

P<doc:LacunaCookbuk::Logic::Secretary>

L<doc:LacunaCookbuk::Logic::ShipCritic>

P<doc:LacunaCookbuk::Logic::ShipCritic>

L<doc:LacunaCookbuk::Logic::Transporter>

P<doc:LacunaCookbuk::Logic::Transporter>
	
=end pod
