unit module HTML::MyHTML::Status;

enum MyHTMLStatus is export (
  MyHTML_STATUS_OK                                   => 0,
  MyHTML_STATUS_ERROR_MEMORY_ALLOCATION              => 1,
  MyHTML_STATUS_THREAD_ERROR_LIST_INIT               => 10,
  MyHTML_STATUS_THREAD_ERROR_ATTR_MALLOC             => 11,
  MyHTML_STATUS_THREAD_ERROR_ATTR_INIT               => 12,
  MyHTML_STATUS_THREAD_ERROR_ATTR_SET                => 13,
  MyHTML_STATUS_THREAD_ERROR_ATTR_DESTROY            => 14,
  MyHTML_STATUS_THREAD_ERROR_NO_SLOTS                => 15,
  MyHTML_STATUS_THREAD_ERROR_BATCH_INIT              => 16,
  MyHTML_STATUS_THREAD_ERROR_WORKER_MALLOC           => 17,
  MyHTML_STATUS_THREAD_ERROR_WORKER_SEM_CREATE       => 18,
  MyHTML_STATUS_THREAD_ERROR_WORKER_THREAD_CREATE    => 19,
  MyHTML_STATUS_THREAD_ERROR_MASTER_THREAD_CREATE    => 20,
  MyHTML_STATUS_THREAD_ERROR_SEM_PREFIX_MALLOC       => 50,
  MyHTML_STATUS_THREAD_ERROR_SEM_CREATE              => 51,
  MyHTML_STATUS_THREAD_ERROR_QUEUE_MALLOC            => 60,
  MyHTML_STATUS_THREAD_ERROR_QUEUE_NODES_MALLOC      => 61,
  MyHTML_STATUS_THREAD_ERROR_QUEUE_NODE_MALLOC       => 62,
  MyHTML_STATUS_RULES_ERROR_MEMORY_ALLOCATION        => 100,
  MyHTML_STATUS_PERF_ERROR_COMPILED_WITHOUT_PERF     => 200,
  MyHTML_STATUS_PERF_ERROR_FIND_CPU_CLOCK            => 201,
  MyHTML_STATUS_TOKENIZER_ERROR_MEMORY_ALLOCATION    => 300,
  MyHTML_STATUS_TAGS_ERROR_MEMORY_ALLOCATION         => 400,
  MyHTML_STATUS_TAGS_ERROR_MCOBJECT_CREATE           => 401,
  MyHTML_STATUS_TAGS_ERROR_MCOBJECT_MALLOC           => 402,
  MyHTML_STATUS_TAGS_ERROR_MCOBJECT_CREATE_NODE      => 403,
  MyHTML_STATUS_TAGS_ERROR_CACHE_MEMORY_ALLOCATION   => 404,
  MyHTML_STATUS_TAGS_ERROR_INDEX_MEMORY_ALLOCATION   => 405,
  MyHTML_STATUS_TREE_ERROR_MEMORY_ALLOCATION         => 500,
  MyHTML_STATUS_TREE_ERROR_MCOBJECT_CREATE           => 501,
  MyHTML_STATUS_TREE_ERROR_MCOBJECT_INIT             => 502,
  MyHTML_STATUS_TREE_ERROR_MCOBJECT_CREATE_NODE      => 503,
  MyHTML_STATUS_ATTR_ERROR_ALLOCATION                => 600,
  MyHTML_STATUS_ATTR_ERROR_CREATE                    => 601
);

sub status(int32 $enum) is export {
  MyHTMLStatus.enums.invert.Hash{$enum};
}

=for DEBUGGING
CHECK {
  say status(0);
  exit 1;
  # %status{61}.say;
}
