module HTML::Entities;
our %entities =
  '&Aa' => {
    '&Aacute;'=> "Á",
    '&Aacute'=> "Á",
  },
  '&aa' => {
    '&aacute;'=> "á",
    '&aacute'=> "á",
  },
  '&Ab' => {
    '&Abreve;'=> "Ă",
  },
  '&ab' => {
    '&abreve;'=> "ă",
  },
  '&ac' => {
    '&ac;'=> "∾",
    '&acd;'=> "∿",
    '&acE;'=> "∾̳",
    '&acirc;'=> "â",
    '&acirc'=> "â",
    '&acute;'=> "´",
    '&acute'=> "´",
    '&acy;'=> "а",
  },
  '&Ac' => {
    '&Acirc;'=> "Â",
    '&Acirc'=> "Â",
    '&Acy;'=> "А",
  },
  '&AE' => {
    '&AElig;'=> "Æ",
    '&AElig'=> "Æ",
  },
  '&ae' => {
    '&aelig;'=> "æ",
    '&aelig'=> "æ",
  },
  '&af' => {
    '&af;'=> "⁡",
    '&afr;'=> "𝔞",
  },
  '&Af' => {
    '&Afr;'=> "𝔄",
  },
  '&Ag' => {
    '&Agrave;'=> "À",
    '&Agrave'=> "À",
  },
  '&ag' => {
    '&agrave;'=> "à",
    '&agrave'=> "à",
  },
  '&al' => {
    '&alefsym;'=> "ℵ",
    '&aleph;'=> "ℵ",
    '&alpha;'=> "α",
  },
  '&Al' => {
    '&Alpha;'=> "Α",
  },
  '&Am' => {
    '&Amacr;'=> "Ā",
  },
  '&am' => {
    '&amacr;'=> "ā",
    '&amalg;'=> "⨿",
    '&amp;'=> "\&",
    '&amp'=> "\&",
  },
  '&AM' => {
    '&AMP;'=> "\&",
    '&AMP'=> "\&",
  },
  '&an' => {
    '&andand;'=> "⩕",
    '&and;'=> "∧",
    '&andd;'=> "⩜",
    '&andslope;'=> "⩘",
    '&andv;'=> "⩚",
    '&ang;'=> "∠",
    '&ange;'=> "⦤",
    '&angle;'=> "∠",
    '&angmsdaa;'=> "⦨",
    '&angmsdab;'=> "⦩",
    '&angmsdac;'=> "⦪",
    '&angmsdad;'=> "⦫",
    '&angmsdae;'=> "⦬",
    '&angmsdaf;'=> "⦭",
    '&angmsdag;'=> "⦮",
    '&angmsdah;'=> "⦯",
    '&angmsd;'=> "∡",
    '&angrt;'=> "∟",
    '&angrtvb;'=> "⊾",
    '&angrtvbd;'=> "⦝",
    '&angsph;'=> "∢",
    '&angst;'=> "Å",
    '&angzarr;'=> "⍼",
  },
  '&An' => {
    '&And;'=> "⩓",
  },
  '&Ao' => {
    '&Aogon;'=> "Ą",
    '&Aopf;'=> "𝔸",
  },
  '&ao' => {
    '&aogon;'=> "ą",
    '&aopf;'=> "𝕒",
  },
  '&ap' => {
    '&apacir;'=> "⩯",
    '&ap;'=> "≈",
    '&apE;'=> "⩰",
    '&ape;'=> "≊",
    '&apid;'=> "≋",
    '&apos;'=> "'",
    '&approx;'=> "≈",
    '&approxeq;'=> "≊",
  },
  '&Ap' => {
    '&ApplyFunction;'=> "⁡",
  },
  '&Ar' => {
    '&Aring;'=> "Å",
    '&Aring'=> "Å",
  },
  '&ar' => {
    '&aring;'=> "å",
    '&aring'=> "å",
  },
  '&As' => {
    '&Ascr;'=> "𝒜",
    '&Assign;'=> "≔",
  },
  '&as' => {
    '&ascr;'=> "𝒶",
    '&ast;'=> "*",
    '&asymp;'=> "≈",
    '&asympeq;'=> "≍",
  },
  '&At' => {
    '&Atilde;'=> "Ã",
    '&Atilde'=> "Ã",
  },
  '&at' => {
    '&atilde;'=> "ã",
    '&atilde'=> "ã",
  },
  '&Au' => {
    '&Auml;'=> "Ä",
    '&Auml'=> "Ä",
  },
  '&au' => {
    '&auml;'=> "ä",
    '&auml'=> "ä",
  },
  '&aw' => {
    '&awconint;'=> "∳",
    '&awint;'=> "⨑",
  },
  '&ba' => {
    '&backcong;'=> "≌",
    '&backepsilon;'=> "϶",
    '&backprime;'=> "‵",
    '&backsim;'=> "∽",
    '&backsimeq;'=> "⋍",
    '&barvee;'=> "⊽",
    '&barwed;'=> "⌅",
    '&barwedge;'=> "⌅",
  },
  '&Ba' => {
    '&Backslash;'=> "∖",
    '&Barv;'=> "⫧",
    '&Barwed;'=> "⌆",
  },
  '&bb' => {
    '&bbrk;'=> "⎵",
    '&bbrktbrk;'=> "⎶",
  },
  '&bc' => {
    '&bcong;'=> "≌",
    '&bcy;'=> "б",
  },
  '&Bc' => {
    '&Bcy;'=> "Б",
  },
  '&bd' => {
    '&bdquo;'=> "„",
  },
  '&be' => {
    '&becaus;'=> "∵",
    '&because;'=> "∵",
    '&bemptyv;'=> "⦰",
    '&bepsi;'=> "϶",
    '&bernou;'=> "ℬ",
    '&beta;'=> "β",
    '&beth;'=> "ℶ",
    '&between;'=> "≬",
  },
  '&Be' => {
    '&Because;'=> "∵",
    '&Bernoullis;'=> "ℬ",
    '&Beta;'=> "Β",
  },
  '&Bf' => {
    '&Bfr;'=> "𝔅",
  },
  '&bf' => {
    '&bfr;'=> "𝔟",
  },
  '&bi' => {
    '&bigcap;'=> "⋂",
    '&bigcirc;'=> "◯",
    '&bigcup;'=> "⋃",
    '&bigodot;'=> "⨀",
    '&bigoplus;'=> "⨁",
    '&bigotimes;'=> "⨂",
    '&bigsqcup;'=> "⨆",
    '&bigstar;'=> "★",
    '&bigtriangledown;'=> "▽",
    '&bigtriangleup;'=> "△",
    '&biguplus;'=> "⨄",
    '&bigvee;'=> "⋁",
    '&bigwedge;'=> "⋀",
  },
  '&bk' => {
    '&bkarow;'=> "⤍",
  },
  '&bl' => {
    '&blacklozenge;'=> "⧫",
    '&blacksquare;'=> "▪",
    '&blacktriangle;'=> "▴",
    '&blacktriangledown;'=> "▾",
    '&blacktriangleleft;'=> "◂",
    '&blacktriangleright;'=> "▸",
    '&blank;'=> "␣",
    '&blk12;'=> "▒",
    '&blk14;'=> "░",
    '&blk34;'=> "▓",
    '&block;'=> "█",
  },
  '&bn' => {
    '&bne;'=> "=⃥",
    '&bnequiv;'=> "≡⃥",
    '&bnot;'=> "⌐",
  },
  '&bN' => {
    '&bNot;'=> "⫭",
  },
  '&Bo' => {
    '&Bopf;'=> "𝔹",
  },
  '&bo' => {
    '&bopf;'=> "𝕓",
    '&bot;'=> "⊥",
    '&bottom;'=> "⊥",
    '&bowtie;'=> "⋈",
    '&boxbox;'=> "⧉",
    '&boxdl;'=> "┐",
    '&boxdL;'=> "╕",
    '&boxDl;'=> "╖",
    '&boxDL;'=> "╗",
    '&boxdr;'=> "┌",
    '&boxdR;'=> "╒",
    '&boxDr;'=> "╓",
    '&boxDR;'=> "╔",
    '&boxh;'=> "─",
    '&boxH;'=> "═",
    '&boxhd;'=> "┬",
    '&boxHd;'=> "╤",
    '&boxhD;'=> "╥",
    '&boxHD;'=> "╦",
    '&boxhu;'=> "┴",
    '&boxHu;'=> "╧",
    '&boxhU;'=> "╨",
    '&boxHU;'=> "╩",
    '&boxminus;'=> "⊟",
    '&boxplus;'=> "⊞",
    '&boxtimes;'=> "⊠",
    '&boxul;'=> "┘",
    '&boxuL;'=> "╛",
    '&boxUl;'=> "╜",
    '&boxUL;'=> "╝",
    '&boxur;'=> "└",
    '&boxuR;'=> "╘",
    '&boxUr;'=> "╙",
    '&boxUR;'=> "╚",
    '&boxv;'=> "│",
    '&boxV;'=> "║",
    '&boxvh;'=> "┼",
    '&boxvH;'=> "╪",
    '&boxVh;'=> "╫",
    '&boxVH;'=> "╬",
    '&boxvl;'=> "┤",
    '&boxvL;'=> "╡",
    '&boxVl;'=> "╢",
    '&boxVL;'=> "╣",
    '&boxvr;'=> "├",
    '&boxvR;'=> "╞",
    '&boxVr;'=> "╟",
    '&boxVR;'=> "╠",
  },
  '&bp' => {
    '&bprime;'=> "‵",
  },
  '&br' => {
    '&breve;'=> "˘",
    '&brvbar;'=> "¦",
    '&brvbar'=> "¦",
  },
  '&Br' => {
    '&Breve;'=> "˘",
  },
  '&bs' => {
    '&bscr;'=> "𝒷",
    '&bsemi;'=> "⁏",
    '&bsim;'=> "∽",
    '&bsime;'=> "⋍",
    '&bsolb;'=> "⧅",
    '&bsol;'=> "\\",
    '&bsolhsub;'=> "⟈",
  },
  '&Bs' => {
    '&Bscr;'=> "ℬ",
  },
  '&bu' => {
    '&bull;'=> "•",
    '&bullet;'=> "•",
    '&bump;'=> "≎",
    '&bumpE;'=> "⪮",
    '&bumpe;'=> "≏",
    '&bumpeq;'=> "≏",
  },
  '&Bu' => {
    '&Bumpeq;'=> "≎",
  },
  '&Ca' => {
    '&Cacute;'=> "Ć",
    '&Cap;'=> "⋒",
    '&CapitalDifferentialD;'=> "ⅅ",
    '&Cayleys;'=> "ℭ",
  },
  '&ca' => {
    '&cacute;'=> "ć",
    '&capand;'=> "⩄",
    '&capbrcup;'=> "⩉",
    '&capcap;'=> "⩋",
    '&cap;'=> "∩",
    '&capcup;'=> "⩇",
    '&capdot;'=> "⩀",
    '&caps;'=> "∩︀",
    '&caret;'=> "⁁",
    '&caron;'=> "ˇ",
  },
  '&cc' => {
    '&ccaps;'=> "⩍",
    '&ccaron;'=> "č",
    '&ccedil;'=> "ç",
    '&ccedil'=> "ç",
    '&ccirc;'=> "ĉ",
    '&ccups;'=> "⩌",
    '&ccupssm;'=> "⩐",
  },
  '&Cc' => {
    '&Ccaron;'=> "Č",
    '&Ccedil;'=> "Ç",
    '&Ccedil'=> "Ç",
    '&Ccirc;'=> "Ĉ",
    '&Cconint;'=> "∰",
  },
  '&Cd' => {
    '&Cdot;'=> "Ċ",
  },
  '&cd' => {
    '&cdot;'=> "ċ",
  },
  '&ce' => {
    '&cedil;'=> "¸",
    '&cedil'=> "¸",
    '&cemptyv;'=> "⦲",
    '&cent;'=> "¢",
    '&cent'=> "¢",
    '&centerdot;'=> "·",
  },
  '&Ce' => {
    '&Cedilla;'=> "¸",
    '&CenterDot;'=> "·",
  },
  '&cf' => {
    '&cfr;'=> "𝔠",
  },
  '&Cf' => {
    '&Cfr;'=> "ℭ",
  },
  '&CH' => {
    '&CHcy;'=> "Ч",
  },
  '&ch' => {
    '&chcy;'=> "ч",
    '&check;'=> "✓",
    '&checkmark;'=> "✓",
    '&chi;'=> "χ",
  },
  '&Ch' => {
    '&Chi;'=> "Χ",
  },
  '&ci' => {
    '&circ;'=> "ˆ",
    '&circeq;'=> "≗",
    '&circlearrowleft;'=> "↺",
    '&circlearrowright;'=> "↻",
    '&circledast;'=> "⊛",
    '&circledcirc;'=> "⊚",
    '&circleddash;'=> "⊝",
    '&circledR;'=> "®",
    '&circledS;'=> "Ⓢ",
    '&cir;'=> "○",
    '&cirE;'=> "⧃",
    '&cire;'=> "≗",
    '&cirfnint;'=> "⨐",
    '&cirmid;'=> "⫯",
    '&cirscir;'=> "⧂",
  },
  '&Ci' => {
    '&CircleDot;'=> "⊙",
    '&CircleMinus;'=> "⊖",
    '&CirclePlus;'=> "⊕",
    '&CircleTimes;'=> "⊗",
  },
  '&Cl' => {
    '&ClockwiseContourIntegral;'=> "∲",
    '&CloseCurlyDoubleQuote;'=> "”",
    '&CloseCurlyQuote;'=> "’",
  },
  '&cl' => {
    '&clubs;'=> "♣",
    '&clubsuit;'=> "♣",
  },
  '&co' => {
    '&colon;'=> ":",
    '&colone;'=> "≔",
    '&coloneq;'=> "≔",
    '&comma;'=> ",",
    '&commat;'=> "\@",
    '&comp;'=> "∁",
    '&compfn;'=> "∘",
    '&complement;'=> "∁",
    '&complexes;'=> "ℂ",
    '&cong;'=> "≅",
    '&congdot;'=> "⩭",
    '&conint;'=> "∮",
    '&copf;'=> "𝕔",
    '&coprod;'=> "∐",
    '&copy;'=> "©",
    '&copy'=> "©",
    '&copysr;'=> "℗",
  },
  '&Co' => {
    '&Colon;'=> "∷",
    '&Colone;'=> "⩴",
    '&Congruent;'=> "≡",
    '&Conint;'=> "∯",
    '&ContourIntegral;'=> "∮",
    '&Copf;'=> "ℂ",
    '&Coproduct;'=> "∐",
    '&CounterClockwiseContourIntegral;'=> "∳",
  },
  '&CO' => {
    '&COPY;'=> "©",
    '&COPY'=> "©",
  },
  '&cr' => {
    '&crarr;'=> "↵",
    '&cross;'=> "✗",
  },
  '&Cr' => {
    '&Cross;'=> "⨯",
  },
  '&Cs' => {
    '&Cscr;'=> "𝒞",
  },
  '&cs' => {
    '&cscr;'=> "𝒸",
    '&csub;'=> "⫏",
    '&csube;'=> "⫑",
    '&csup;'=> "⫐",
    '&csupe;'=> "⫒",
  },
  '&ct' => {
    '&ctdot;'=> "⋯",
  },
  '&cu' => {
    '&cudarrl;'=> "⤸",
    '&cudarrr;'=> "⤵",
    '&cuepr;'=> "⋞",
    '&cuesc;'=> "⋟",
    '&cularr;'=> "↶",
    '&cularrp;'=> "⤽",
    '&cupbrcap;'=> "⩈",
    '&cupcap;'=> "⩆",
    '&cup;'=> "∪",
    '&cupcup;'=> "⩊",
    '&cupdot;'=> "⊍",
    '&cupor;'=> "⩅",
    '&cups;'=> "∪︀",
    '&curarr;'=> "↷",
    '&curarrm;'=> "⤼",
    '&curlyeqprec;'=> "⋞",
    '&curlyeqsucc;'=> "⋟",
    '&curlyvee;'=> "⋎",
    '&curlywedge;'=> "⋏",
    '&curren;'=> "¤",
    '&curren'=> "¤",
    '&curvearrowleft;'=> "↶",
    '&curvearrowright;'=> "↷",
    '&cuvee;'=> "⋎",
    '&cuwed;'=> "⋏",
  },
  '&Cu' => {
    '&CupCap;'=> "≍",
    '&Cup;'=> "⋓",
  },
  '&cw' => {
    '&cwconint;'=> "∲",
    '&cwint;'=> "∱",
  },
  '&cy' => {
    '&cylcty;'=> "⌭",
  },
  '&da' => {
    '&dagger;'=> "†",
    '&daleth;'=> "ℸ",
    '&darr;'=> "↓",
    '&dash;'=> "‐",
    '&dashv;'=> "⊣",
  },
  '&Da' => {
    '&Dagger;'=> "‡",
    '&Darr;'=> "↡",
    '&Dashv;'=> "⫤",
  },
  '&dA' => {
    '&dArr;'=> "⇓",
  },
  '&db' => {
    '&dbkarow;'=> "⤏",
    '&dblac;'=> "˝",
  },
  '&Dc' => {
    '&Dcaron;'=> "Ď",
    '&Dcy;'=> "Д",
  },
  '&dc' => {
    '&dcaron;'=> "ď",
    '&dcy;'=> "д",
  },
  '&dd' => {
    '&ddagger;'=> "‡",
    '&ddarr;'=> "⇊",
    '&dd;'=> "ⅆ",
    '&ddotseq;'=> "⩷",
  },
  '&DD' => {
    '&DD;'=> "ⅅ",
    '&DDotrahd;'=> "⤑",
  },
  '&de' => {
    '&deg;'=> "°",
    '&deg'=> "°",
    '&delta;'=> "δ",
    '&demptyv;'=> "⦱",
  },
  '&De' => {
    '&Del;'=> "∇",
    '&Delta;'=> "Δ",
  },
  '&df' => {
    '&dfisht;'=> "⥿",
    '&dfr;'=> "𝔡",
  },
  '&Df' => {
    '&Dfr;'=> "𝔇",
  },
  '&dH' => {
    '&dHar;'=> "⥥",
  },
  '&dh' => {
    '&dharl;'=> "⇃",
    '&dharr;'=> "⇂",
  },
  '&Di' => {
    '&DiacriticalAcute;'=> "´",
    '&DiacriticalDot;'=> "˙",
    '&DiacriticalDoubleAcute;'=> "˝",
    '&DiacriticalGrave;'=> "`",
    '&DiacriticalTilde;'=> "˜",
    '&Diamond;'=> "⋄",
    '&DifferentialD;'=> "ⅆ",
  },
  '&di' => {
    '&diam;'=> "⋄",
    '&diamond;'=> "⋄",
    '&diamondsuit;'=> "♦",
    '&diams;'=> "♦",
    '&die;'=> "¨",
    '&digamma;'=> "ϝ",
    '&disin;'=> "⋲",
    '&div;'=> "÷",
    '&divide;'=> "÷",
    '&divide'=> "÷",
    '&divideontimes;'=> "⋇",
    '&divonx;'=> "⋇",
  },
  '&DJ' => {
    '&DJcy;'=> "Ђ",
  },
  '&dj' => {
    '&djcy;'=> "ђ",
  },
  '&dl' => {
    '&dlcorn;'=> "⌞",
    '&dlcrop;'=> "⌍",
  },
  '&do' => {
    '&dollar;'=> "\$",
    '&dopf;'=> "𝕕",
    '&dot;'=> "˙",
    '&doteq;'=> "≐",
    '&doteqdot;'=> "≑",
    '&dotminus;'=> "∸",
    '&dotplus;'=> "∔",
    '&dotsquare;'=> "⊡",
    '&doublebarwedge;'=> "⌆",
    '&downarrow;'=> "↓",
    '&downdownarrows;'=> "⇊",
    '&downharpoonleft;'=> "⇃",
    '&downharpoonright;'=> "⇂",
  },
  '&Do' => {
    '&Dopf;'=> "𝔻",
    '&Dot;'=> "¨",
    '&DotDot;'=> "⃜",
    '&DotEqual;'=> "≐",
    '&DoubleContourIntegral;'=> "∯",
    '&DoubleDot;'=> "¨",
    '&DoubleDownArrow;'=> "⇓",
    '&DoubleLeftArrow;'=> "⇐",
    '&DoubleLeftRightArrow;'=> "⇔",
    '&DoubleLeftTee;'=> "⫤",
    '&DoubleLongLeftArrow;'=> "⟸",
    '&DoubleLongLeftRightArrow;'=> "⟺",
    '&DoubleLongRightArrow;'=> "⟹",
    '&DoubleRightArrow;'=> "⇒",
    '&DoubleRightTee;'=> "⊨",
    '&DoubleUpArrow;'=> "⇑",
    '&DoubleUpDownArrow;'=> "⇕",
    '&DoubleVerticalBar;'=> "∥",
    '&DownArrowBar;'=> "⤓",
    '&DownArrow;'=> "↓",
    '&Downarrow;'=> "⇓",
    '&DownArrowUpArrow;'=> "⇵",
    '&DownBreve;'=> "̑",
    '&DownLeftRightVector;'=> "⥐",
    '&DownLeftTeeVector;'=> "⥞",
    '&DownLeftVectorBar;'=> "⥖",
    '&DownLeftVector;'=> "↽",
    '&DownRightTeeVector;'=> "⥟",
    '&DownRightVectorBar;'=> "⥗",
    '&DownRightVector;'=> "⇁",
    '&DownTeeArrow;'=> "↧",
    '&DownTee;'=> "⊤",
  },
  '&dr' => {
    '&drbkarow;'=> "⤐",
    '&drcorn;'=> "⌟",
    '&drcrop;'=> "⌌",
  },
  '&Ds' => {
    '&Dscr;'=> "𝒟",
    '&Dstrok;'=> "Đ",
  },
  '&ds' => {
    '&dscr;'=> "𝒹",
    '&dscy;'=> "ѕ",
    '&dsol;'=> "⧶",
    '&dstrok;'=> "đ",
  },
  '&DS' => {
    '&DScy;'=> "Ѕ",
  },
  '&dt' => {
    '&dtdot;'=> "⋱",
    '&dtri;'=> "▿",
    '&dtrif;'=> "▾",
  },
  '&du' => {
    '&duarr;'=> "⇵",
    '&duhar;'=> "⥯",
  },
  '&dw' => {
    '&dwangle;'=> "⦦",
  },
  '&DZ' => {
    '&DZcy;'=> "Џ",
  },
  '&dz' => {
    '&dzcy;'=> "џ",
    '&dzigrarr;'=> "⟿",
  },
  '&Ea' => {
    '&Eacute;'=> "É",
    '&Eacute'=> "É",
  },
  '&ea' => {
    '&eacute;'=> "é",
    '&eacute'=> "é",
    '&easter;'=> "⩮",
  },
  '&Ec' => {
    '&Ecaron;'=> "Ě",
    '&Ecirc;'=> "Ê",
    '&Ecirc'=> "Ê",
    '&Ecy;'=> "Э",
  },
  '&ec' => {
    '&ecaron;'=> "ě",
    '&ecirc;'=> "ê",
    '&ecirc'=> "ê",
    '&ecir;'=> "≖",
    '&ecolon;'=> "≕",
    '&ecy;'=> "э",
  },
  '&eD' => {
    '&eDDot;'=> "⩷",
    '&eDot;'=> "≑",
  },
  '&Ed' => {
    '&Edot;'=> "Ė",
  },
  '&ed' => {
    '&edot;'=> "ė",
  },
  '&ee' => {
    '&ee;'=> "ⅇ",
  },
  '&ef' => {
    '&efDot;'=> "≒",
    '&efr;'=> "𝔢",
  },
  '&Ef' => {
    '&Efr;'=> "𝔈",
  },
  '&eg' => {
    '&eg;'=> "⪚",
    '&egrave;'=> "è",
    '&egrave'=> "è",
    '&egs;'=> "⪖",
    '&egsdot;'=> "⪘",
  },
  '&Eg' => {
    '&Egrave;'=> "È",
    '&Egrave'=> "È",
  },
  '&el' => {
    '&el;'=> "⪙",
    '&elinters;'=> "⏧",
    '&ell;'=> "ℓ",
    '&els;'=> "⪕",
    '&elsdot;'=> "⪗",
  },
  '&El' => {
    '&Element;'=> "∈",
  },
  '&Em' => {
    '&Emacr;'=> "Ē",
    '&EmptySmallSquare;'=> "◻",
    '&EmptyVerySmallSquare;'=> "▫",
  },
  '&em' => {
    '&emacr;'=> "ē",
    '&empty;'=> "∅",
    '&emptyset;'=> "∅",
    '&emptyv;'=> "∅",
    '&emsp13;'=> " ",
    '&emsp14;'=> " ",
    '&emsp;'=> " ",
  },
  '&EN' => {
    '&ENG;'=> "Ŋ",
  },
  '&en' => {
    '&eng;'=> "ŋ",
    '&ensp;'=> " ",
  },
  '&Eo' => {
    '&Eogon;'=> "Ę",
    '&Eopf;'=> "𝔼",
  },
  '&eo' => {
    '&eogon;'=> "ę",
    '&eopf;'=> "𝕖",
  },
  '&ep' => {
    '&epar;'=> "⋕",
    '&eparsl;'=> "⧣",
    '&eplus;'=> "⩱",
    '&epsi;'=> "ε",
    '&epsilon;'=> "ε",
    '&epsiv;'=> "ϵ",
  },
  '&Ep' => {
    '&Epsilon;'=> "Ε",
  },
  '&eq' => {
    '&eqcirc;'=> "≖",
    '&eqcolon;'=> "≕",
    '&eqsim;'=> "≂",
    '&eqslantgtr;'=> "⪖",
    '&eqslantless;'=> "⪕",
    '&equals;'=> "=",
    '&equest;'=> "≟",
    '&equiv;'=> "≡",
    '&equivDD;'=> "⩸",
    '&eqvparsl;'=> "⧥",
  },
  '&Eq' => {
    '&Equal;'=> "⩵",
    '&EqualTilde;'=> "≂",
    '&Equilibrium;'=> "⇌",
  },
  '&er' => {
    '&erarr;'=> "⥱",
    '&erDot;'=> "≓",
  },
  '&es' => {
    '&escr;'=> "ℯ",
    '&esdot;'=> "≐",
    '&esim;'=> "≂",
  },
  '&Es' => {
    '&Escr;'=> "ℰ",
    '&Esim;'=> "⩳",
  },
  '&Et' => {
    '&Eta;'=> "Η",
  },
  '&et' => {
    '&eta;'=> "η",
    '&eth;'=> "ð",
    '&eth'=> "ð",
  },
  '&ET' => {
    '&ETH;'=> "Ð",
    '&ETH'=> "Ð",
  },
  '&Eu' => {
    '&Euml;'=> "Ë",
    '&Euml'=> "Ë",
  },
  '&eu' => {
    '&euml;'=> "ë",
    '&euml'=> "ë",
    '&euro;'=> "€",
  },
  '&ex' => {
    '&excl;'=> "!",
    '&exist;'=> "∃",
    '&expectation;'=> "ℰ",
    '&exponentiale;'=> "ⅇ",
  },
  '&Ex' => {
    '&Exists;'=> "∃",
    '&ExponentialE;'=> "ⅇ",
  },
  '&fa' => {
    '&fallingdotseq;'=> "≒",
  },
  '&Fc' => {
    '&Fcy;'=> "Ф",
  },
  '&fc' => {
    '&fcy;'=> "ф",
  },
  '&fe' => {
    '&female;'=> "♀",
  },
  '&ff' => {
    '&ffilig;'=> "ﬃ",
    '&fflig;'=> "ﬀ",
    '&ffllig;'=> "ﬄ",
    '&ffr;'=> "𝔣",
  },
  '&Ff' => {
    '&Ffr;'=> "𝔉",
  },
  '&fi' => {
    '&filig;'=> "ﬁ",
  },
  '&Fi' => {
    '&FilledSmallSquare;'=> "◼",
    '&FilledVerySmallSquare;'=> "▪",
  },
  '&fj' => {
    '&fjlig;'=> "fj",
  },
  '&fl' => {
    '&flat;'=> "♭",
    '&fllig;'=> "ﬂ",
    '&fltns;'=> "▱",
  },
  '&fn' => {
    '&fnof;'=> "ƒ",
  },
  '&Fo' => {
    '&Fopf;'=> "𝔽",
    '&ForAll;'=> "∀",
    '&Fouriertrf;'=> "ℱ",
  },
  '&fo' => {
    '&fopf;'=> "𝕗",
    '&forall;'=> "∀",
    '&fork;'=> "⋔",
    '&forkv;'=> "⫙",
  },
  '&fp' => {
    '&fpartint;'=> "⨍",
  },
  '&fr' => {
    '&frac12;'=> "½",
    '&frac12'=> "½",
    '&frac13;'=> "⅓",
    '&frac14;'=> "¼",
    '&frac14'=> "¼",
    '&frac15;'=> "⅕",
    '&frac16;'=> "⅙",
    '&frac18;'=> "⅛",
    '&frac23;'=> "⅔",
    '&frac25;'=> "⅖",
    '&frac34;'=> "¾",
    '&frac34'=> "¾",
    '&frac35;'=> "⅗",
    '&frac38;'=> "⅜",
    '&frac45;'=> "⅘",
    '&frac56;'=> "⅚",
    '&frac58;'=> "⅝",
    '&frac78;'=> "⅞",
    '&frasl;'=> "⁄",
    '&frown;'=> "⌢",
  },
  '&fs' => {
    '&fscr;'=> "𝒻",
  },
  '&Fs' => {
    '&Fscr;'=> "ℱ",
  },
  '&ga' => {
    '&gacute;'=> "ǵ",
    '&gamma;'=> "γ",
    '&gammad;'=> "ϝ",
    '&gap;'=> "⪆",
  },
  '&Ga' => {
    '&Gamma;'=> "Γ",
    '&Gammad;'=> "Ϝ",
  },
  '&Gb' => {
    '&Gbreve;'=> "Ğ",
  },
  '&gb' => {
    '&gbreve;'=> "ğ",
  },
  '&Gc' => {
    '&Gcedil;'=> "Ģ",
    '&Gcirc;'=> "Ĝ",
    '&Gcy;'=> "Г",
  },
  '&gc' => {
    '&gcirc;'=> "ĝ",
    '&gcy;'=> "г",
  },
  '&Gd' => {
    '&Gdot;'=> "Ġ",
  },
  '&gd' => {
    '&gdot;'=> "ġ",
  },
  '&ge' => {
    '&ge;'=> "≥",
    '&gel;'=> "⋛",
    '&geq;'=> "≥",
    '&geqq;'=> "≧",
    '&geqslant;'=> "⩾",
    '&gescc;'=> "⪩",
    '&ges;'=> "⩾",
    '&gesdot;'=> "⪀",
    '&gesdoto;'=> "⪂",
    '&gesdotol;'=> "⪄",
    '&gesl;'=> "⋛︀",
    '&gesles;'=> "⪔",
  },
  '&gE' => {
    '&gE;'=> "≧",
    '&gEl;'=> "⪌",
  },
  '&Gf' => {
    '&Gfr;'=> "𝔊",
  },
  '&gf' => {
    '&gfr;'=> "𝔤",
  },
  '&gg' => {
    '&gg;'=> "≫",
    '&ggg;'=> "⋙",
  },
  '&Gg' => {
    '&Gg;'=> "⋙",
  },
  '&gi' => {
    '&gimel;'=> "ℷ",
  },
  '&GJ' => {
    '&GJcy;'=> "Ѓ",
  },
  '&gj' => {
    '&gjcy;'=> "ѓ",
  },
  '&gl' => {
    '&gla;'=> "⪥",
    '&gl;'=> "≷",
    '&glE;'=> "⪒",
    '&glj;'=> "⪤",
  },
  '&gn' => {
    '&gnap;'=> "⪊",
    '&gnapprox;'=> "⪊",
    '&gne;'=> "⪈",
    '&gnE;'=> "≩",
    '&gneq;'=> "⪈",
    '&gneqq;'=> "≩",
    '&gnsim;'=> "⋧",
  },
  '&Go' => {
    '&Gopf;'=> "𝔾",
  },
  '&go' => {
    '&gopf;'=> "𝕘",
  },
  '&gr' => {
    '&grave;'=> "`",
  },
  '&Gr' => {
    '&GreaterEqual;'=> "≥",
    '&GreaterEqualLess;'=> "⋛",
    '&GreaterFullEqual;'=> "≧",
    '&GreaterGreater;'=> "⪢",
    '&GreaterLess;'=> "≷",
    '&GreaterSlantEqual;'=> "⩾",
    '&GreaterTilde;'=> "≳",
  },
  '&Gs' => {
    '&Gscr;'=> "𝒢",
  },
  '&gs' => {
    '&gscr;'=> "ℊ",
    '&gsim;'=> "≳",
    '&gsime;'=> "⪎",
    '&gsiml;'=> "⪐",
  },
  '&gt' => {
    '&gtcc;'=> "⪧",
    '&gtcir;'=> "⩺",
    '&gt;'=> ">",
    '&gt'=> ">",
    '&gtdot;'=> "⋗",
    '&gtlPar;'=> "⦕",
    '&gtquest;'=> "⩼",
    '&gtrapprox;'=> "⪆",
    '&gtrarr;'=> "⥸",
    '&gtrdot;'=> "⋗",
    '&gtreqless;'=> "⋛",
    '&gtreqqless;'=> "⪌",
    '&gtrless;'=> "≷",
    '&gtrsim;'=> "≳",
  },
  '&GT' => {
    '&GT;'=> ">",
    '&GT'=> ">",
  },
  '&Gt' => {
    '&Gt;'=> "≫",
  },
  '&gv' => {
    '&gvertneqq;'=> "≩︀",
    '&gvnE;'=> "≩︀",
  },
  '&Ha' => {
    '&Hacek;'=> "ˇ",
    '&Hat;'=> "^",
  },
  '&ha' => {
    '&hairsp;'=> " ",
    '&half;'=> "½",
    '&hamilt;'=> "ℋ",
    '&hardcy;'=> "ъ",
    '&harrcir;'=> "⥈",
    '&harr;'=> "↔",
    '&harrw;'=> "↭",
  },
  '&HA' => {
    '&HARDcy;'=> "Ъ",
  },
  '&hA' => {
    '&hArr;'=> "⇔",
  },
  '&hb' => {
    '&hbar;'=> "ℏ",
  },
  '&Hc' => {
    '&Hcirc;'=> "Ĥ",
  },
  '&hc' => {
    '&hcirc;'=> "ĥ",
  },
  '&he' => {
    '&hearts;'=> "♥",
    '&heartsuit;'=> "♥",
    '&hellip;'=> "…",
    '&hercon;'=> "⊹",
  },
  '&hf' => {
    '&hfr;'=> "𝔥",
  },
  '&Hf' => {
    '&Hfr;'=> "ℌ",
  },
  '&Hi' => {
    '&HilbertSpace;'=> "ℋ",
  },
  '&hk' => {
    '&hksearow;'=> "⤥",
    '&hkswarow;'=> "⤦",
  },
  '&ho' => {
    '&hoarr;'=> "⇿",
    '&homtht;'=> "∻",
    '&hookleftarrow;'=> "↩",
    '&hookrightarrow;'=> "↪",
    '&hopf;'=> "𝕙",
    '&horbar;'=> "―",
  },
  '&Ho' => {
    '&Hopf;'=> "ℍ",
    '&HorizontalLine;'=> "─",
  },
  '&hs' => {
    '&hscr;'=> "𝒽",
    '&hslash;'=> "ℏ",
    '&hstrok;'=> "ħ",
  },
  '&Hs' => {
    '&Hscr;'=> "ℋ",
    '&Hstrok;'=> "Ħ",
  },
  '&Hu' => {
    '&HumpDownHump;'=> "≎",
    '&HumpEqual;'=> "≏",
  },
  '&hy' => {
    '&hybull;'=> "⁃",
    '&hyphen;'=> "‐",
  },
  '&Ia' => {
    '&Iacute;'=> "Í",
    '&Iacute'=> "Í",
  },
  '&ia' => {
    '&iacute;'=> "í",
    '&iacute'=> "í",
  },
  '&ic' => {
    '&ic;'=> "⁣",
    '&icirc;'=> "î",
    '&icirc'=> "î",
    '&icy;'=> "и",
  },
  '&Ic' => {
    '&Icirc;'=> "Î",
    '&Icirc'=> "Î",
    '&Icy;'=> "И",
  },
  '&Id' => {
    '&Idot;'=> "İ",
  },
  '&IE' => {
    '&IEcy;'=> "Е",
  },
  '&ie' => {
    '&iecy;'=> "е",
    '&iexcl;'=> "¡",
    '&iexcl'=> "¡",
  },
  '&if' => {
    '&iff;'=> "⇔",
    '&ifr;'=> "𝔦",
  },
  '&If' => {
    '&Ifr;'=> "ℑ",
  },
  '&Ig' => {
    '&Igrave;'=> "Ì",
    '&Igrave'=> "Ì",
  },
  '&ig' => {
    '&igrave;'=> "ì",
    '&igrave'=> "ì",
  },
  '&ii' => {
    '&ii;'=> "ⅈ",
    '&iiiint;'=> "⨌",
    '&iiint;'=> "∭",
    '&iinfin;'=> "⧜",
    '&iiota;'=> "℩",
  },
  '&IJ' => {
    '&IJlig;'=> "Ĳ",
  },
  '&ij' => {
    '&ijlig;'=> "ĳ",
  },
  '&Im' => {
    '&Imacr;'=> "Ī",
    '&ImaginaryI;'=> "ⅈ",
    '&Im;'=> "ℑ",
    '&Implies;'=> "⇒",
  },
  '&im' => {
    '&imacr;'=> "ī",
    '&image;'=> "ℑ",
    '&imagline;'=> "ℐ",
    '&imagpart;'=> "ℑ",
    '&imath;'=> "ı",
    '&imof;'=> "⊷",
    '&imped;'=> "Ƶ",
  },
  '&in' => {
    '&incare;'=> "℅",
    '&in;'=> "∈",
    '&infin;'=> "∞",
    '&infintie;'=> "⧝",
    '&inodot;'=> "ı",
    '&intcal;'=> "⊺",
    '&int;'=> "∫",
    '&integers;'=> "ℤ",
    '&intercal;'=> "⊺",
    '&intlarhk;'=> "⨗",
    '&intprod;'=> "⨼",
  },
  '&In' => {
    '&Int;'=> "∬",
    '&Integral;'=> "∫",
    '&Intersection;'=> "⋂",
    '&InvisibleComma;'=> "⁣",
    '&InvisibleTimes;'=> "⁢",
  },
  '&IO' => {
    '&IOcy;'=> "Ё",
  },
  '&io' => {
    '&iocy;'=> "ё",
    '&iogon;'=> "į",
    '&iopf;'=> "𝕚",
    '&iota;'=> "ι",
  },
  '&Io' => {
    '&Iogon;'=> "Į",
    '&Iopf;'=> "𝕀",
    '&Iota;'=> "Ι",
  },
  '&ip' => {
    '&iprod;'=> "⨼",
  },
  '&iq' => {
    '&iquest;'=> "¿",
    '&iquest'=> "¿",
  },
  '&is' => {
    '&iscr;'=> "𝒾",
    '&isin;'=> "∈",
    '&isindot;'=> "⋵",
    '&isinE;'=> "⋹",
    '&isins;'=> "⋴",
    '&isinsv;'=> "⋳",
    '&isinv;'=> "∈",
  },
  '&Is' => {
    '&Iscr;'=> "ℐ",
  },
  '&it' => {
    '&it;'=> "⁢",
    '&itilde;'=> "ĩ",
  },
  '&It' => {
    '&Itilde;'=> "Ĩ",
  },
  '&Iu' => {
    '&Iukcy;'=> "І",
    '&Iuml;'=> "Ï",
    '&Iuml'=> "Ï",
  },
  '&iu' => {
    '&iukcy;'=> "і",
    '&iuml;'=> "ï",
    '&iuml'=> "ï",
  },
  '&Jc' => {
    '&Jcirc;'=> "Ĵ",
    '&Jcy;'=> "Й",
  },
  '&jc' => {
    '&jcirc;'=> "ĵ",
    '&jcy;'=> "й",
  },
  '&Jf' => {
    '&Jfr;'=> "𝔍",
  },
  '&jf' => {
    '&jfr;'=> "𝔧",
  },
  '&jm' => {
    '&jmath;'=> "ȷ",
  },
  '&Jo' => {
    '&Jopf;'=> "𝕁",
  },
  '&jo' => {
    '&jopf;'=> "𝕛",
  },
  '&Js' => {
    '&Jscr;'=> "𝒥",
    '&Jsercy;'=> "Ј",
  },
  '&js' => {
    '&jscr;'=> "𝒿",
    '&jsercy;'=> "ј",
  },
  '&Ju' => {
    '&Jukcy;'=> "Є",
  },
  '&ju' => {
    '&jukcy;'=> "є",
  },
  '&Ka' => {
    '&Kappa;'=> "Κ",
  },
  '&ka' => {
    '&kappa;'=> "κ",
    '&kappav;'=> "ϰ",
  },
  '&Kc' => {
    '&Kcedil;'=> "Ķ",
    '&Kcy;'=> "К",
  },
  '&kc' => {
    '&kcedil;'=> "ķ",
    '&kcy;'=> "к",
  },
  '&Kf' => {
    '&Kfr;'=> "𝔎",
  },
  '&kf' => {
    '&kfr;'=> "𝔨",
  },
  '&kg' => {
    '&kgreen;'=> "ĸ",
  },
  '&KH' => {
    '&KHcy;'=> "Х",
  },
  '&kh' => {
    '&khcy;'=> "х",
  },
  '&KJ' => {
    '&KJcy;'=> "Ќ",
  },
  '&kj' => {
    '&kjcy;'=> "ќ",
  },
  '&Ko' => {
    '&Kopf;'=> "𝕂",
  },
  '&ko' => {
    '&kopf;'=> "𝕜",
  },
  '&Ks' => {
    '&Kscr;'=> "𝒦",
  },
  '&ks' => {
    '&kscr;'=> "𝓀",
  },
  '&lA' => {
    '&lAarr;'=> "⇚",
    '&lArr;'=> "⇐",
    '&lAtail;'=> "⤛",
  },
  '&La' => {
    '&Lacute;'=> "Ĺ",
    '&Lambda;'=> "Λ",
    '&Lang;'=> "⟪",
    '&Laplacetrf;'=> "ℒ",
    '&Larr;'=> "↞",
  },
  '&la' => {
    '&lacute;'=> "ĺ",
    '&laemptyv;'=> "⦴",
    '&lagran;'=> "ℒ",
    '&lambda;'=> "λ",
    '&lang;'=> "⟨",
    '&langd;'=> "⦑",
    '&langle;'=> "⟨",
    '&lap;'=> "⪅",
    '&laquo;'=> "«",
    '&laquo'=> "«",
    '&larrb;'=> "⇤",
    '&larrbfs;'=> "⤟",
    '&larr;'=> "←",
    '&larrfs;'=> "⤝",
    '&larrhk;'=> "↩",
    '&larrlp;'=> "↫",
    '&larrpl;'=> "⤹",
    '&larrsim;'=> "⥳",
    '&larrtl;'=> "↢",
    '&latail;'=> "⤙",
    '&lat;'=> "⪫",
    '&late;'=> "⪭",
    '&lates;'=> "⪭︀",
  },
  '&lb' => {
    '&lbarr;'=> "⤌",
    '&lbbrk;'=> "❲",
    '&lbrace;'=> "\{",
    '&lbrack;'=> "[",
    '&lbrke;'=> "⦋",
    '&lbrksld;'=> "⦏",
    '&lbrkslu;'=> "⦍",
  },
  '&lB' => {
    '&lBarr;'=> "⤎",
  },
  '&Lc' => {
    '&Lcaron;'=> "Ľ",
    '&Lcedil;'=> "Ļ",
    '&Lcy;'=> "Л",
  },
  '&lc' => {
    '&lcaron;'=> "ľ",
    '&lcedil;'=> "ļ",
    '&lceil;'=> "⌈",
    '&lcub;'=> "\{",
    '&lcy;'=> "л",
  },
  '&ld' => {
    '&ldca;'=> "⤶",
    '&ldquo;'=> "“",
    '&ldquor;'=> "„",
    '&ldrdhar;'=> "⥧",
    '&ldrushar;'=> "⥋",
    '&ldsh;'=> "↲",
  },
  '&le' => {
    '&le;'=> "≤",
    '&leftarrow;'=> "←",
    '&leftarrowtail;'=> "↢",
    '&leftharpoondown;'=> "↽",
    '&leftharpoonup;'=> "↼",
    '&leftleftarrows;'=> "⇇",
    '&leftrightarrow;'=> "↔",
    '&leftrightarrows;'=> "⇆",
    '&leftrightharpoons;'=> "⇋",
    '&leftrightsquigarrow;'=> "↭",
    '&leftthreetimes;'=> "⋋",
    '&leg;'=> "⋚",
    '&leq;'=> "≤",
    '&leqq;'=> "≦",
    '&leqslant;'=> "⩽",
    '&lescc;'=> "⪨",
    '&les;'=> "⩽",
    '&lesdot;'=> "⩿",
    '&lesdoto;'=> "⪁",
    '&lesdotor;'=> "⪃",
    '&lesg;'=> "⋚︀",
    '&lesges;'=> "⪓",
    '&lessapprox;'=> "⪅",
    '&lessdot;'=> "⋖",
    '&lesseqgtr;'=> "⋚",
    '&lesseqqgtr;'=> "⪋",
    '&lessgtr;'=> "≶",
    '&lesssim;'=> "≲",
  },
  '&lE' => {
    '&lE;'=> "≦",
    '&lEg;'=> "⪋",
  },
  '&Le' => {
    '&LeftAngleBracket;'=> "⟨",
    '&LeftArrowBar;'=> "⇤",
    '&LeftArrow;'=> "←",
    '&Leftarrow;'=> "⇐",
    '&LeftArrowRightArrow;'=> "⇆",
    '&LeftCeiling;'=> "⌈",
    '&LeftDoubleBracket;'=> "⟦",
    '&LeftDownTeeVector;'=> "⥡",
    '&LeftDownVectorBar;'=> "⥙",
    '&LeftDownVector;'=> "⇃",
    '&LeftFloor;'=> "⌊",
    '&LeftRightArrow;'=> "↔",
    '&Leftrightarrow;'=> "⇔",
    '&LeftRightVector;'=> "⥎",
    '&LeftTeeArrow;'=> "↤",
    '&LeftTee;'=> "⊣",
    '&LeftTeeVector;'=> "⥚",
    '&LeftTriangleBar;'=> "⧏",
    '&LeftTriangle;'=> "⊲",
    '&LeftTriangleEqual;'=> "⊴",
    '&LeftUpDownVector;'=> "⥑",
    '&LeftUpTeeVector;'=> "⥠",
    '&LeftUpVectorBar;'=> "⥘",
    '&LeftUpVector;'=> "↿",
    '&LeftVectorBar;'=> "⥒",
    '&LeftVector;'=> "↼",
    '&LessEqualGreater;'=> "⋚",
    '&LessFullEqual;'=> "≦",
    '&LessGreater;'=> "≶",
    '&LessLess;'=> "⪡",
    '&LessSlantEqual;'=> "⩽",
    '&LessTilde;'=> "≲",
  },
  '&lf' => {
    '&lfisht;'=> "⥼",
    '&lfloor;'=> "⌊",
    '&lfr;'=> "𝔩",
  },
  '&Lf' => {
    '&Lfr;'=> "𝔏",
  },
  '&lg' => {
    '&lg;'=> "≶",
    '&lgE;'=> "⪑",
  },
  '&lH' => {
    '&lHar;'=> "⥢",
  },
  '&lh' => {
    '&lhard;'=> "↽",
    '&lharu;'=> "↼",
    '&lharul;'=> "⥪",
    '&lhblk;'=> "▄",
  },
  '&LJ' => {
    '&LJcy;'=> "Љ",
  },
  '&lj' => {
    '&ljcy;'=> "љ",
  },
  '&ll' => {
    '&llarr;'=> "⇇",
    '&ll;'=> "≪",
    '&llcorner;'=> "⌞",
    '&llhard;'=> "⥫",
    '&lltri;'=> "◺",
  },
  '&Ll' => {
    '&Ll;'=> "⋘",
    '&Lleftarrow;'=> "⇚",
  },
  '&Lm' => {
    '&Lmidot;'=> "Ŀ",
  },
  '&lm' => {
    '&lmidot;'=> "ŀ",
    '&lmoustache;'=> "⎰",
    '&lmoust;'=> "⎰",
  },
  '&ln' => {
    '&lnap;'=> "⪉",
    '&lnapprox;'=> "⪉",
    '&lne;'=> "⪇",
    '&lnE;'=> "≨",
    '&lneq;'=> "⪇",
    '&lneqq;'=> "≨",
    '&lnsim;'=> "⋦",
  },
  '&lo' => {
    '&loang;'=> "⟬",
    '&loarr;'=> "⇽",
    '&lobrk;'=> "⟦",
    '&longleftarrow;'=> "⟵",
    '&longleftrightarrow;'=> "⟷",
    '&longmapsto;'=> "⟼",
    '&longrightarrow;'=> "⟶",
    '&looparrowleft;'=> "↫",
    '&looparrowright;'=> "↬",
    '&lopar;'=> "⦅",
    '&lopf;'=> "𝕝",
    '&loplus;'=> "⨭",
    '&lotimes;'=> "⨴",
    '&lowast;'=> "∗",
    '&lowbar;'=> "_",
    '&loz;'=> "◊",
    '&lozenge;'=> "◊",
    '&lozf;'=> "⧫",
  },
  '&Lo' => {
    '&LongLeftArrow;'=> "⟵",
    '&Longleftarrow;'=> "⟸",
    '&LongLeftRightArrow;'=> "⟷",
    '&Longleftrightarrow;'=> "⟺",
    '&LongRightArrow;'=> "⟶",
    '&Longrightarrow;'=> "⟹",
    '&Lopf;'=> "𝕃",
    '&LowerLeftArrow;'=> "↙",
    '&LowerRightArrow;'=> "↘",
  },
  '&lp' => {
    '&lpar;'=> "(",
    '&lparlt;'=> "⦓",
  },
  '&lr' => {
    '&lrarr;'=> "⇆",
    '&lrcorner;'=> "⌟",
    '&lrhar;'=> "⇋",
    '&lrhard;'=> "⥭",
    '&lrm;'=> "‎",
    '&lrtri;'=> "⊿",
  },
  '&ls' => {
    '&lsaquo;'=> "‹",
    '&lscr;'=> "𝓁",
    '&lsh;'=> "↰",
    '&lsim;'=> "≲",
    '&lsime;'=> "⪍",
    '&lsimg;'=> "⪏",
    '&lsqb;'=> "[",
    '&lsquo;'=> "‘",
    '&lsquor;'=> "‚",
    '&lstrok;'=> "ł",
  },
  '&Ls' => {
    '&Lscr;'=> "ℒ",
    '&Lsh;'=> "↰",
    '&Lstrok;'=> "Ł",
  },
  '&lt' => {
    '&ltcc;'=> "⪦",
    '&ltcir;'=> "⩹",
    '&lt;'=> "<",
    '&lt'=> "<",
    '&ltdot;'=> "⋖",
    '&lthree;'=> "⋋",
    '&ltimes;'=> "⋉",
    '&ltlarr;'=> "⥶",
    '&ltquest;'=> "⩻",
    '&ltri;'=> "◃",
    '&ltrie;'=> "⊴",
    '&ltrif;'=> "◂",
    '&ltrPar;'=> "⦖",
  },
  '&LT' => {
    '&LT;'=> "<",
    '&LT'=> "<",
  },
  '&Lt' => {
    '&Lt;'=> "≪",
  },
  '&lu' => {
    '&lurdshar;'=> "⥊",
    '&luruhar;'=> "⥦",
  },
  '&lv' => {
    '&lvertneqq;'=> "≨︀",
    '&lvnE;'=> "≨︀",
  },
  '&ma' => {
    '&macr;'=> "¯",
    '&macr'=> "¯",
    '&male;'=> "♂",
    '&malt;'=> "✠",
    '&maltese;'=> "✠",
    '&map;'=> "↦",
    '&mapsto;'=> "↦",
    '&mapstodown;'=> "↧",
    '&mapstoleft;'=> "↤",
    '&mapstoup;'=> "↥",
    '&marker;'=> "▮",
  },
  '&Ma' => {
    '&Map;'=> "⤅",
  },
  '&mc' => {
    '&mcomma;'=> "⨩",
    '&mcy;'=> "м",
  },
  '&Mc' => {
    '&Mcy;'=> "М",
  },
  '&md' => {
    '&mdash;'=> "—",
  },
  '&mD' => {
    '&mDDot;'=> "∺",
  },
  '&me' => {
    '&measuredangle;'=> "∡",
  },
  '&Me' => {
    '&MediumSpace;'=> " ",
    '&Mellintrf;'=> "ℳ",
  },
  '&Mf' => {
    '&Mfr;'=> "𝔐",
  },
  '&mf' => {
    '&mfr;'=> "𝔪",
  },
  '&mh' => {
    '&mho;'=> "℧",
  },
  '&mi' => {
    '&micro;'=> "µ",
    '&micro'=> "µ",
    '&midast;'=> "*",
    '&midcir;'=> "⫰",
    '&mid;'=> "∣",
    '&middot;'=> "·",
    '&middot'=> "·",
    '&minusb;'=> "⊟",
    '&minus;'=> "−",
    '&minusd;'=> "∸",
    '&minusdu;'=> "⨪",
  },
  '&Mi' => {
    '&MinusPlus;'=> "∓",
  },
  '&ml' => {
    '&mlcp;'=> "⫛",
    '&mldr;'=> "…",
  },
  '&mn' => {
    '&mnplus;'=> "∓",
  },
  '&mo' => {
    '&models;'=> "⊧",
    '&mopf;'=> "𝕞",
  },
  '&Mo' => {
    '&Mopf;'=> "𝕄",
  },
  '&mp' => {
    '&mp;'=> "∓",
  },
  '&ms' => {
    '&mscr;'=> "𝓂",
    '&mstpos;'=> "∾",
  },
  '&Ms' => {
    '&Mscr;'=> "ℳ",
  },
  '&Mu' => {
    '&Mu;'=> "Μ",
  },
  '&mu' => {
    '&mu;'=> "μ",
    '&multimap;'=> "⊸",
    '&mumap;'=> "⊸",
  },
  '&na' => {
    '&nabla;'=> "∇",
    '&nacute;'=> "ń",
    '&nang;'=> "∠⃒",
    '&nap;'=> "≉",
    '&napE;'=> "⩰̸",
    '&napid;'=> "≋̸",
    '&napos;'=> "ŉ",
    '&napprox;'=> "≉",
    '&natural;'=> "♮",
    '&naturals;'=> "ℕ",
    '&natur;'=> "♮",
  },
  '&Na' => {
    '&Nacute;'=> "Ń",
  },
  '&nb' => {
    '&nbsp;'=> " ",
    '&nbsp'=> " ",
    '&nbump;'=> "≎̸",
    '&nbumpe;'=> "≏̸",
  },
  '&nc' => {
    '&ncap;'=> "⩃",
    '&ncaron;'=> "ň",
    '&ncedil;'=> "ņ",
    '&ncong;'=> "≇",
    '&ncongdot;'=> "⩭̸",
    '&ncup;'=> "⩂",
    '&ncy;'=> "н",
  },
  '&Nc' => {
    '&Ncaron;'=> "Ň",
    '&Ncedil;'=> "Ņ",
    '&Ncy;'=> "Н",
  },
  '&nd' => {
    '&ndash;'=> "–",
  },
  '&ne' => {
    '&nearhk;'=> "⤤",
    '&nearr;'=> "↗",
    '&neArr;'=> "⇗",
    '&nearrow;'=> "↗",
    '&ne;'=> "≠",
    '&nedot;'=> "≐̸",
    '&nequiv;'=> "≢",
    '&nesear;'=> "⤨",
    '&nesim;'=> "≂̸",
    '&nexist;'=> "∄",
    '&nexists;'=> "∄",
  },
  '&Ne' => {
    '&NegativeMediumSpace;'=> "​",
    '&NegativeThickSpace;'=> "​",
    '&NegativeThinSpace;'=> "​",
    '&NegativeVeryThinSpace;'=> "​",
    '&NestedGreaterGreater;'=> "≫",
    '&NestedLessLess;'=> "≪",
    '&NewLine;'=> "\n",
  },
  '&Nf' => {
    '&Nfr;'=> "𝔑",
  },
  '&nf' => {
    '&nfr;'=> "𝔫",
  },
  '&ng' => {
    '&ngE;'=> "≧̸",
    '&nge;'=> "≱",
    '&ngeq;'=> "≱",
    '&ngeqq;'=> "≧̸",
    '&ngeqslant;'=> "⩾̸",
    '&nges;'=> "⩾̸",
    '&ngsim;'=> "≵",
    '&ngt;'=> "≯",
    '&ngtr;'=> "≯",
  },
  '&nG' => {
    '&nGg;'=> "⋙̸",
    '&nGt;'=> "≫⃒",
    '&nGtv;'=> "≫̸",
  },
  '&nh' => {
    '&nharr;'=> "↮",
    '&nhArr;'=> "⇎",
    '&nhpar;'=> "⫲",
  },
  '&ni' => {
    '&ni;'=> "∋",
    '&nis;'=> "⋼",
    '&nisd;'=> "⋺",
    '&niv;'=> "∋",
  },
  '&NJ' => {
    '&NJcy;'=> "Њ",
  },
  '&nj' => {
    '&njcy;'=> "њ",
  },
  '&nl' => {
    '&nlarr;'=> "↚",
    '&nlArr;'=> "⇍",
    '&nldr;'=> "‥",
    '&nlE;'=> "≦̸",
    '&nle;'=> "≰",
    '&nleftarrow;'=> "↚",
    '&nleftrightarrow;'=> "↮",
    '&nleq;'=> "≰",
    '&nleqq;'=> "≦̸",
    '&nleqslant;'=> "⩽̸",
    '&nles;'=> "⩽̸",
    '&nless;'=> "≮",
    '&nlsim;'=> "≴",
    '&nlt;'=> "≮",
    '&nltri;'=> "⋪",
    '&nltrie;'=> "⋬",
  },
  '&nL' => {
    '&nLeftarrow;'=> "⇍",
    '&nLeftrightarrow;'=> "⇎",
    '&nLl;'=> "⋘̸",
    '&nLt;'=> "≪⃒",
    '&nLtv;'=> "≪̸",
  },
  '&nm' => {
    '&nmid;'=> "∤",
  },
  '&No' => {
    '&NoBreak;'=> "⁠",
    '&NonBreakingSpace;'=> " ",
    '&Nopf;'=> "ℕ",
    '&Not;'=> "⫬",
    '&NotCongruent;'=> "≢",
    '&NotCupCap;'=> "≭",
    '&NotDoubleVerticalBar;'=> "∦",
    '&NotElement;'=> "∉",
    '&NotEqual;'=> "≠",
    '&NotEqualTilde;'=> "≂̸",
    '&NotExists;'=> "∄",
    '&NotGreater;'=> "≯",
    '&NotGreaterEqual;'=> "≱",
    '&NotGreaterFullEqual;'=> "≧̸",
    '&NotGreaterGreater;'=> "≫̸",
    '&NotGreaterLess;'=> "≹",
    '&NotGreaterSlantEqual;'=> "⩾̸",
    '&NotGreaterTilde;'=> "≵",
    '&NotHumpDownHump;'=> "≎̸",
    '&NotHumpEqual;'=> "≏̸",
    '&NotLeftTriangleBar;'=> "⧏̸",
    '&NotLeftTriangle;'=> "⋪",
    '&NotLeftTriangleEqual;'=> "⋬",
    '&NotLess;'=> "≮",
    '&NotLessEqual;'=> "≰",
    '&NotLessGreater;'=> "≸",
    '&NotLessLess;'=> "≪̸",
    '&NotLessSlantEqual;'=> "⩽̸",
    '&NotLessTilde;'=> "≴",
    '&NotNestedGreaterGreater;'=> "⪢̸",
    '&NotNestedLessLess;'=> "⪡̸",
    '&NotPrecedes;'=> "⊀",
    '&NotPrecedesEqual;'=> "⪯̸",
    '&NotPrecedesSlantEqual;'=> "⋠",
    '&NotReverseElement;'=> "∌",
    '&NotRightTriangleBar;'=> "⧐̸",
    '&NotRightTriangle;'=> "⋫",
    '&NotRightTriangleEqual;'=> "⋭",
    '&NotSquareSubset;'=> "⊏̸",
    '&NotSquareSubsetEqual;'=> "⋢",
    '&NotSquareSuperset;'=> "⊐̸",
    '&NotSquareSupersetEqual;'=> "⋣",
    '&NotSubset;'=> "⊂⃒",
    '&NotSubsetEqual;'=> "⊈",
    '&NotSucceeds;'=> "⊁",
    '&NotSucceedsEqual;'=> "⪰̸",
    '&NotSucceedsSlantEqual;'=> "⋡",
    '&NotSucceedsTilde;'=> "≿̸",
    '&NotSuperset;'=> "⊃⃒",
    '&NotSupersetEqual;'=> "⊉",
    '&NotTilde;'=> "≁",
    '&NotTildeEqual;'=> "≄",
    '&NotTildeFullEqual;'=> "≇",
    '&NotTildeTilde;'=> "≉",
    '&NotVerticalBar;'=> "∤",
  },
  '&no' => {
    '&nopf;'=> "𝕟",
    '&not;'=> "¬",
    '&not'=> "¬",
    '&notin;'=> "∉",
    '&notindot;'=> "⋵̸",
    '&notinE;'=> "⋹̸",
    '&notinva;'=> "∉",
    '&notinvb;'=> "⋷",
    '&notinvc;'=> "⋶",
    '&notni;'=> "∌",
    '&notniva;'=> "∌",
    '&notnivb;'=> "⋾",
    '&notnivc;'=> "⋽",
  },
  '&np' => {
    '&nparallel;'=> "∦",
    '&npar;'=> "∦",
    '&nparsl;'=> "⫽⃥",
    '&npart;'=> "∂̸",
    '&npolint;'=> "⨔",
    '&npr;'=> "⊀",
    '&nprcue;'=> "⋠",
    '&nprec;'=> "⊀",
    '&npreceq;'=> "⪯̸",
    '&npre;'=> "⪯̸",
  },
  '&nr' => {
    '&nrarrc;'=> "⤳̸",
    '&nrarr;'=> "↛",
    '&nrArr;'=> "⇏",
    '&nrarrw;'=> "↝̸",
    '&nrightarrow;'=> "↛",
    '&nrtri;'=> "⋫",
    '&nrtrie;'=> "⋭",
  },
  '&nR' => {
    '&nRightarrow;'=> "⇏",
  },
  '&ns' => {
    '&nsc;'=> "⊁",
    '&nsccue;'=> "⋡",
    '&nsce;'=> "⪰̸",
    '&nscr;'=> "𝓃",
    '&nshortmid;'=> "∤",
    '&nshortparallel;'=> "∦",
    '&nsim;'=> "≁",
    '&nsime;'=> "≄",
    '&nsimeq;'=> "≄",
    '&nsmid;'=> "∤",
    '&nspar;'=> "∦",
    '&nsqsube;'=> "⋢",
    '&nsqsupe;'=> "⋣",
    '&nsub;'=> "⊄",
    '&nsubE;'=> "⫅̸",
    '&nsube;'=> "⊈",
    '&nsubset;'=> "⊂⃒",
    '&nsubseteq;'=> "⊈",
    '&nsubseteqq;'=> "⫅̸",
    '&nsucc;'=> "⊁",
    '&nsucceq;'=> "⪰̸",
    '&nsup;'=> "⊅",
    '&nsupE;'=> "⫆̸",
    '&nsupe;'=> "⊉",
    '&nsupset;'=> "⊃⃒",
    '&nsupseteq;'=> "⊉",
    '&nsupseteqq;'=> "⫆̸",
  },
  '&Ns' => {
    '&Nscr;'=> "𝒩",
  },
  '&nt' => {
    '&ntgl;'=> "≹",
    '&ntilde;'=> "ñ",
    '&ntilde'=> "ñ",
    '&ntlg;'=> "≸",
    '&ntriangleleft;'=> "⋪",
    '&ntrianglelefteq;'=> "⋬",
    '&ntriangleright;'=> "⋫",
    '&ntrianglerighteq;'=> "⋭",
  },
  '&Nt' => {
    '&Ntilde;'=> "Ñ",
    '&Ntilde'=> "Ñ",
  },
  '&Nu' => {
    '&Nu;'=> "Ν",
  },
  '&nu' => {
    '&nu;'=> "ν",
    '&num;'=> "#",
    '&numero;'=> "№",
    '&numsp;'=> " ",
  },
  '&nv' => {
    '&nvap;'=> "≍⃒",
    '&nvdash;'=> "⊬",
    '&nvDash;'=> "⊭",
    '&nvge;'=> "≥⃒",
    '&nvgt;'=> ">⃒",
    '&nvHarr;'=> "⤄",
    '&nvinfin;'=> "⧞",
    '&nvlArr;'=> "⤂",
    '&nvle;'=> "≤⃒",
    '&nvlt;'=> "<⃒",
    '&nvltrie;'=> "⊴⃒",
    '&nvrArr;'=> "⤃",
    '&nvrtrie;'=> "⊵⃒",
    '&nvsim;'=> "∼⃒",
  },
  '&nV' => {
    '&nVdash;'=> "⊮",
    '&nVDash;'=> "⊯",
  },
  '&nw' => {
    '&nwarhk;'=> "⤣",
    '&nwarr;'=> "↖",
    '&nwArr;'=> "⇖",
    '&nwarrow;'=> "↖",
    '&nwnear;'=> "⤧",
  },
  '&Oa' => {
    '&Oacute;'=> "Ó",
    '&Oacute'=> "Ó",
  },
  '&oa' => {
    '&oacute;'=> "ó",
    '&oacute'=> "ó",
    '&oast;'=> "⊛",
  },
  '&Oc' => {
    '&Ocirc;'=> "Ô",
    '&Ocirc'=> "Ô",
    '&Ocy;'=> "О",
  },
  '&oc' => {
    '&ocirc;'=> "ô",
    '&ocirc'=> "ô",
    '&ocir;'=> "⊚",
    '&ocy;'=> "о",
  },
  '&od' => {
    '&odash;'=> "⊝",
    '&odblac;'=> "ő",
    '&odiv;'=> "⨸",
    '&odot;'=> "⊙",
    '&odsold;'=> "⦼",
  },
  '&Od' => {
    '&Odblac;'=> "Ő",
  },
  '&OE' => {
    '&OElig;'=> "Œ",
  },
  '&oe' => {
    '&oelig;'=> "œ",
  },
  '&of' => {
    '&ofcir;'=> "⦿",
    '&ofr;'=> "𝔬",
  },
  '&Of' => {
    '&Ofr;'=> "𝔒",
  },
  '&og' => {
    '&ogon;'=> "˛",
    '&ograve;'=> "ò",
    '&ograve'=> "ò",
    '&ogt;'=> "⧁",
  },
  '&Og' => {
    '&Ograve;'=> "Ò",
    '&Ograve'=> "Ò",
  },
  '&oh' => {
    '&ohbar;'=> "⦵",
    '&ohm;'=> "Ω",
  },
  '&oi' => {
    '&oint;'=> "∮",
  },
  '&ol' => {
    '&olarr;'=> "↺",
    '&olcir;'=> "⦾",
    '&olcross;'=> "⦻",
    '&oline;'=> "‾",
    '&olt;'=> "⧀",
  },
  '&Om' => {
    '&Omacr;'=> "Ō",
    '&Omega;'=> "Ω",
    '&Omicron;'=> "Ο",
  },
  '&om' => {
    '&omacr;'=> "ō",
    '&omega;'=> "ω",
    '&omicron;'=> "ο",
    '&omid;'=> "⦶",
    '&ominus;'=> "⊖",
  },
  '&Oo' => {
    '&Oopf;'=> "𝕆",
  },
  '&oo' => {
    '&oopf;'=> "𝕠",
  },
  '&op' => {
    '&opar;'=> "⦷",
    '&operp;'=> "⦹",
    '&oplus;'=> "⊕",
  },
  '&Op' => {
    '&OpenCurlyDoubleQuote;'=> "“",
    '&OpenCurlyQuote;'=> "‘",
  },
  '&or' => {
    '&orarr;'=> "↻",
    '&or;'=> "∨",
    '&ord;'=> "⩝",
    '&order;'=> "ℴ",
    '&orderof;'=> "ℴ",
    '&ordf;'=> "ª",
    '&ordf'=> "ª",
    '&ordm;'=> "º",
    '&ordm'=> "º",
    '&origof;'=> "⊶",
    '&oror;'=> "⩖",
    '&orslope;'=> "⩗",
    '&orv;'=> "⩛",
  },
  '&Or' => {
    '&Or;'=> "⩔",
  },
  '&oS' => {
    '&oS;'=> "Ⓢ",
  },
  '&Os' => {
    '&Oscr;'=> "𝒪",
    '&Oslash;'=> "Ø",
    '&Oslash'=> "Ø",
  },
  '&os' => {
    '&oscr;'=> "ℴ",
    '&oslash;'=> "ø",
    '&oslash'=> "ø",
    '&osol;'=> "⊘",
  },
  '&Ot' => {
    '&Otilde;'=> "Õ",
    '&Otilde'=> "Õ",
    '&Otimes;'=> "⨷",
  },
  '&ot' => {
    '&otilde;'=> "õ",
    '&otilde'=> "õ",
    '&otimesas;'=> "⨶",
    '&otimes;'=> "⊗",
  },
  '&Ou' => {
    '&Ouml;'=> "Ö",
    '&Ouml'=> "Ö",
  },
  '&ou' => {
    '&ouml;'=> "ö",
    '&ouml'=> "ö",
  },
  '&ov' => {
    '&ovbar;'=> "⌽",
  },
  '&Ov' => {
    '&OverBar;'=> "‾",
    '&OverBrace;'=> "⏞",
    '&OverBracket;'=> "⎴",
    '&OverParenthesis;'=> "⏜",
  },
  '&pa' => {
    '&para;'=> "¶",
    '&para'=> "¶",
    '&parallel;'=> "∥",
    '&par;'=> "∥",
    '&parsim;'=> "⫳",
    '&parsl;'=> "⫽",
    '&part;'=> "∂",
  },
  '&Pa' => {
    '&PartialD;'=> "∂",
  },
  '&Pc' => {
    '&Pcy;'=> "П",
  },
  '&pc' => {
    '&pcy;'=> "п",
  },
  '&pe' => {
    '&percnt;'=> "\%",
    '&period;'=> ".",
    '&permil;'=> "‰",
    '&perp;'=> "⊥",
    '&pertenk;'=> "‱",
  },
  '&Pf' => {
    '&Pfr;'=> "𝔓",
  },
  '&pf' => {
    '&pfr;'=> "𝔭",
  },
  '&Ph' => {
    '&Phi;'=> "Φ",
  },
  '&ph' => {
    '&phi;'=> "φ",
    '&phiv;'=> "ϕ",
    '&phmmat;'=> "ℳ",
    '&phone;'=> "☎",
  },
  '&Pi' => {
    '&Pi;'=> "Π",
  },
  '&pi' => {
    '&pi;'=> "π",
    '&pitchfork;'=> "⋔",
    '&piv;'=> "ϖ",
  },
  '&pl' => {
    '&planck;'=> "ℏ",
    '&planckh;'=> "ℎ",
    '&plankv;'=> "ℏ",
    '&plusacir;'=> "⨣",
    '&plusb;'=> "⊞",
    '&pluscir;'=> "⨢",
    '&plus;'=> "+",
    '&plusdo;'=> "∔",
    '&plusdu;'=> "⨥",
    '&pluse;'=> "⩲",
    '&plusmn;'=> "±",
    '&plusmn'=> "±",
    '&plussim;'=> "⨦",
    '&plustwo;'=> "⨧",
  },
  '&Pl' => {
    '&PlusMinus;'=> "±",
  },
  '&pm' => {
    '&pm;'=> "±",
  },
  '&Po' => {
    '&Poincareplane;'=> "ℌ",
    '&Popf;'=> "ℙ",
  },
  '&po' => {
    '&pointint;'=> "⨕",
    '&popf;'=> "𝕡",
    '&pound;'=> "£",
    '&pound'=> "£",
  },
  '&pr' => {
    '&prap;'=> "⪷",
    '&pr;'=> "≺",
    '&prcue;'=> "≼",
    '&precapprox;'=> "⪷",
    '&prec;'=> "≺",
    '&preccurlyeq;'=> "≼",
    '&preceq;'=> "⪯",
    '&precnapprox;'=> "⪹",
    '&precneqq;'=> "⪵",
    '&precnsim;'=> "⋨",
    '&pre;'=> "⪯",
    '&prE;'=> "⪳",
    '&precsim;'=> "≾",
    '&prime;'=> "′",
    '&primes;'=> "ℙ",
    '&prnap;'=> "⪹",
    '&prnE;'=> "⪵",
    '&prnsim;'=> "⋨",
    '&prod;'=> "∏",
    '&profalar;'=> "⌮",
    '&profline;'=> "⌒",
    '&profsurf;'=> "⌓",
    '&prop;'=> "∝",
    '&propto;'=> "∝",
    '&prsim;'=> "≾",
    '&prurel;'=> "⊰",
  },
  '&Pr' => {
    '&Pr;'=> "⪻",
    '&Precedes;'=> "≺",
    '&PrecedesEqual;'=> "⪯",
    '&PrecedesSlantEqual;'=> "≼",
    '&PrecedesTilde;'=> "≾",
    '&Prime;'=> "″",
    '&Product;'=> "∏",
    '&Proportional;'=> "∝",
    '&Proportion;'=> "∷",
  },
  '&Ps' => {
    '&Pscr;'=> "𝒫",
    '&Psi;'=> "Ψ",
  },
  '&ps' => {
    '&pscr;'=> "𝓅",
    '&psi;'=> "ψ",
  },
  '&pu' => {
    '&puncsp;'=> " ",
  },
  '&Qf' => {
    '&Qfr;'=> "𝔔",
  },
  '&qf' => {
    '&qfr;'=> "𝔮",
  },
  '&qi' => {
    '&qint;'=> "⨌",
  },
  '&qo' => {
    '&qopf;'=> "𝕢",
  },
  '&Qo' => {
    '&Qopf;'=> "ℚ",
  },
  '&qp' => {
    '&qprime;'=> "⁗",
  },
  '&Qs' => {
    '&Qscr;'=> "𝒬",
  },
  '&qs' => {
    '&qscr;'=> "𝓆",
  },
  '&qu' => {
    '&quaternions;'=> "ℍ",
    '&quatint;'=> "⨖",
    '&quest;'=> "?",
    '&questeq;'=> "≟",
    '&quot;'=> "\"",
    '&quot'=> "\"",
  },
  '&QU' => {
    '&QUOT;'=> "\"",
    '&QUOT'=> "\"",
  },
  '&rA' => {
    '&rAarr;'=> "⇛",
    '&rArr;'=> "⇒",
    '&rAtail;'=> "⤜",
  },
  '&ra' => {
    '&race;'=> "∽̱",
    '&racute;'=> "ŕ",
    '&radic;'=> "√",
    '&raemptyv;'=> "⦳",
    '&rang;'=> "⟩",
    '&rangd;'=> "⦒",
    '&range;'=> "⦥",
    '&rangle;'=> "⟩",
    '&raquo;'=> "»",
    '&raquo'=> "»",
    '&rarrap;'=> "⥵",
    '&rarrb;'=> "⇥",
    '&rarrbfs;'=> "⤠",
    '&rarrc;'=> "⤳",
    '&rarr;'=> "→",
    '&rarrfs;'=> "⤞",
    '&rarrhk;'=> "↪",
    '&rarrlp;'=> "↬",
    '&rarrpl;'=> "⥅",
    '&rarrsim;'=> "⥴",
    '&rarrtl;'=> "↣",
    '&rarrw;'=> "↝",
    '&ratail;'=> "⤚",
    '&ratio;'=> "∶",
    '&rationals;'=> "ℚ",
  },
  '&Ra' => {
    '&Racute;'=> "Ŕ",
    '&Rang;'=> "⟫",
    '&Rarr;'=> "↠",
    '&Rarrtl;'=> "⤖",
  },
  '&rb' => {
    '&rbarr;'=> "⤍",
    '&rbbrk;'=> "❳",
    '&rbrace;'=> "}",
    '&rbrack;'=> "]",
    '&rbrke;'=> "⦌",
    '&rbrksld;'=> "⦎",
    '&rbrkslu;'=> "⦐",
  },
  '&rB' => {
    '&rBarr;'=> "⤏",
  },
  '&RB' => {
    '&RBarr;'=> "⤐",
  },
  '&Rc' => {
    '&Rcaron;'=> "Ř",
    '&Rcedil;'=> "Ŗ",
    '&Rcy;'=> "Р",
  },
  '&rc' => {
    '&rcaron;'=> "ř",
    '&rcedil;'=> "ŗ",
    '&rceil;'=> "⌉",
    '&rcub;'=> "}",
    '&rcy;'=> "р",
  },
  '&rd' => {
    '&rdca;'=> "⤷",
    '&rdldhar;'=> "⥩",
    '&rdquo;'=> "”",
    '&rdquor;'=> "”",
    '&rdsh;'=> "↳",
  },
  '&re' => {
    '&real;'=> "ℜ",
    '&realine;'=> "ℛ",
    '&realpart;'=> "ℜ",
    '&reals;'=> "ℝ",
    '&rect;'=> "▭",
    '&reg;'=> "®",
    '&reg'=> "®",
  },
  '&Re' => {
    '&Re;'=> "ℜ",
    '&ReverseElement;'=> "∋",
    '&ReverseEquilibrium;'=> "⇋",
    '&ReverseUpEquilibrium;'=> "⥯",
  },
  '&RE' => {
    '&REG;'=> "®",
    '&REG'=> "®",
  },
  '&rf' => {
    '&rfisht;'=> "⥽",
    '&rfloor;'=> "⌋",
    '&rfr;'=> "𝔯",
  },
  '&Rf' => {
    '&Rfr;'=> "ℜ",
  },
  '&rH' => {
    '&rHar;'=> "⥤",
  },
  '&rh' => {
    '&rhard;'=> "⇁",
    '&rharu;'=> "⇀",
    '&rharul;'=> "⥬",
    '&rho;'=> "ρ",
    '&rhov;'=> "ϱ",
  },
  '&Rh' => {
    '&Rho;'=> "Ρ",
  },
  '&Ri' => {
    '&RightAngleBracket;'=> "⟩",
    '&RightArrowBar;'=> "⇥",
    '&RightArrow;'=> "→",
    '&Rightarrow;'=> "⇒",
    '&RightArrowLeftArrow;'=> "⇄",
    '&RightCeiling;'=> "⌉",
    '&RightDoubleBracket;'=> "⟧",
    '&RightDownTeeVector;'=> "⥝",
    '&RightDownVectorBar;'=> "⥕",
    '&RightDownVector;'=> "⇂",
    '&RightFloor;'=> "⌋",
    '&RightTeeArrow;'=> "↦",
    '&RightTee;'=> "⊢",
    '&RightTeeVector;'=> "⥛",
    '&RightTriangleBar;'=> "⧐",
    '&RightTriangle;'=> "⊳",
    '&RightTriangleEqual;'=> "⊵",
    '&RightUpDownVector;'=> "⥏",
    '&RightUpTeeVector;'=> "⥜",
    '&RightUpVectorBar;'=> "⥔",
    '&RightUpVector;'=> "↾",
    '&RightVectorBar;'=> "⥓",
    '&RightVector;'=> "⇀",
  },
  '&ri' => {
    '&rightarrow;'=> "→",
    '&rightarrowtail;'=> "↣",
    '&rightharpoondown;'=> "⇁",
    '&rightharpoonup;'=> "⇀",
    '&rightleftarrows;'=> "⇄",
    '&rightleftharpoons;'=> "⇌",
    '&rightrightarrows;'=> "⇉",
    '&rightsquigarrow;'=> "↝",
    '&rightthreetimes;'=> "⋌",
    '&ring;'=> "˚",
    '&risingdotseq;'=> "≓",
  },
  '&rl' => {
    '&rlarr;'=> "⇄",
    '&rlhar;'=> "⇌",
    '&rlm;'=> "‏",
  },
  '&rm' => {
    '&rmoustache;'=> "⎱",
    '&rmoust;'=> "⎱",
  },
  '&rn' => {
    '&rnmid;'=> "⫮",
  },
  '&ro' => {
    '&roang;'=> "⟭",
    '&roarr;'=> "⇾",
    '&robrk;'=> "⟧",
    '&ropar;'=> "⦆",
    '&ropf;'=> "𝕣",
    '&roplus;'=> "⨮",
    '&rotimes;'=> "⨵",
  },
  '&Ro' => {
    '&Ropf;'=> "ℝ",
    '&RoundImplies;'=> "⥰",
  },
  '&rp' => {
    '&rpar;'=> ")",
    '&rpargt;'=> "⦔",
    '&rppolint;'=> "⨒",
  },
  '&rr' => {
    '&rrarr;'=> "⇉",
  },
  '&Rr' => {
    '&Rrightarrow;'=> "⇛",
  },
  '&rs' => {
    '&rsaquo;'=> "›",
    '&rscr;'=> "𝓇",
    '&rsh;'=> "↱",
    '&rsqb;'=> "]",
    '&rsquo;'=> "’",
    '&rsquor;'=> "’",
  },
  '&Rs' => {
    '&Rscr;'=> "ℛ",
    '&Rsh;'=> "↱",
  },
  '&rt' => {
    '&rthree;'=> "⋌",
    '&rtimes;'=> "⋊",
    '&rtri;'=> "▹",
    '&rtrie;'=> "⊵",
    '&rtrif;'=> "▸",
    '&rtriltri;'=> "⧎",
  },
  '&Ru' => {
    '&RuleDelayed;'=> "⧴",
  },
  '&ru' => {
    '&ruluhar;'=> "⥨",
  },
  '&rx' => {
    '&rx;'=> "℞",
  },
  '&Sa' => {
    '&Sacute;'=> "Ś",
  },
  '&sa' => {
    '&sacute;'=> "ś",
  },
  '&sb' => {
    '&sbquo;'=> "‚",
  },
  '&sc' => {
    '&scap;'=> "⪸",
    '&scaron;'=> "š",
    '&sc;'=> "≻",
    '&sccue;'=> "≽",
    '&sce;'=> "⪰",
    '&scE;'=> "⪴",
    '&scedil;'=> "ş",
    '&scirc;'=> "ŝ",
    '&scnap;'=> "⪺",
    '&scnE;'=> "⪶",
    '&scnsim;'=> "⋩",
    '&scpolint;'=> "⨓",
    '&scsim;'=> "≿",
    '&scy;'=> "с",
  },
  '&Sc' => {
    '&Scaron;'=> "Š",
    '&Sc;'=> "⪼",
    '&Scedil;'=> "Ş",
    '&Scirc;'=> "Ŝ",
    '&Scy;'=> "С",
  },
  '&sd' => {
    '&sdotb;'=> "⊡",
    '&sdot;'=> "⋅",
    '&sdote;'=> "⩦",
  },
  '&se' => {
    '&searhk;'=> "⤥",
    '&searr;'=> "↘",
    '&seArr;'=> "⇘",
    '&searrow;'=> "↘",
    '&sect;'=> "§",
    '&sect'=> "§",
    '&semi;'=> ";",
    '&seswar;'=> "⤩",
    '&setminus;'=> "∖",
    '&setmn;'=> "∖",
    '&sext;'=> "✶",
  },
  '&Sf' => {
    '&Sfr;'=> "𝔖",
  },
  '&sf' => {
    '&sfr;'=> "𝔰",
    '&sfrown;'=> "⌢",
  },
  '&sh' => {
    '&sharp;'=> "♯",
    '&shchcy;'=> "щ",
    '&shcy;'=> "ш",
    '&shortmid;'=> "∣",
    '&shortparallel;'=> "∥",
    '&shy;'=> "­",
    '&shy'=> "­",
  },
  '&SH' => {
    '&SHCHcy;'=> "Щ",
    '&SHcy;'=> "Ш",
  },
  '&Sh' => {
    '&ShortDownArrow;'=> "↓",
    '&ShortLeftArrow;'=> "←",
    '&ShortRightArrow;'=> "→",
    '&ShortUpArrow;'=> "↑",
  },
  '&Si' => {
    '&Sigma;'=> "Σ",
  },
  '&si' => {
    '&sigma;'=> "σ",
    '&sigmaf;'=> "ς",
    '&sigmav;'=> "ς",
    '&sim;'=> "∼",
    '&simdot;'=> "⩪",
    '&sime;'=> "≃",
    '&simeq;'=> "≃",
    '&simg;'=> "⪞",
    '&simgE;'=> "⪠",
    '&siml;'=> "⪝",
    '&simlE;'=> "⪟",
    '&simne;'=> "≆",
    '&simplus;'=> "⨤",
    '&simrarr;'=> "⥲",
  },
  '&sl' => {
    '&slarr;'=> "←",
  },
  '&Sm' => {
    '&SmallCircle;'=> "∘",
  },
  '&sm' => {
    '&smallsetminus;'=> "∖",
    '&smashp;'=> "⨳",
    '&smeparsl;'=> "⧤",
    '&smid;'=> "∣",
    '&smile;'=> "⌣",
    '&smt;'=> "⪪",
    '&smte;'=> "⪬",
    '&smtes;'=> "⪬︀",
  },
  '&SO' => {
    '&SOFTcy;'=> "Ь",
  },
  '&so' => {
    '&softcy;'=> "ь",
    '&solbar;'=> "⌿",
    '&solb;'=> "⧄",
    '&sol;'=> "/",
    '&sopf;'=> "𝕤",
  },
  '&So' => {
    '&Sopf;'=> "𝕊",
  },
  '&sp' => {
    '&spades;'=> "♠",
    '&spadesuit;'=> "♠",
    '&spar;'=> "∥",
  },
  '&sq' => {
    '&sqcap;'=> "⊓",
    '&sqcaps;'=> "⊓︀",
    '&sqcup;'=> "⊔",
    '&sqcups;'=> "⊔︀",
    '&sqsub;'=> "⊏",
    '&sqsube;'=> "⊑",
    '&sqsubset;'=> "⊏",
    '&sqsubseteq;'=> "⊑",
    '&sqsup;'=> "⊐",
    '&sqsupe;'=> "⊒",
    '&sqsupset;'=> "⊐",
    '&sqsupseteq;'=> "⊒",
    '&square;'=> "□",
    '&squarf;'=> "▪",
    '&squ;'=> "□",
    '&squf;'=> "▪",
  },
  '&Sq' => {
    '&Sqrt;'=> "√",
    '&Square;'=> "□",
    '&SquareIntersection;'=> "⊓",
    '&SquareSubset;'=> "⊏",
    '&SquareSubsetEqual;'=> "⊑",
    '&SquareSuperset;'=> "⊐",
    '&SquareSupersetEqual;'=> "⊒",
    '&SquareUnion;'=> "⊔",
  },
  '&sr' => {
    '&srarr;'=> "→",
  },
  '&Ss' => {
    '&Sscr;'=> "𝒮",
  },
  '&ss' => {
    '&sscr;'=> "𝓈",
    '&ssetmn;'=> "∖",
    '&ssmile;'=> "⌣",
    '&sstarf;'=> "⋆",
  },
  '&St' => {
    '&Star;'=> "⋆",
  },
  '&st' => {
    '&star;'=> "☆",
    '&starf;'=> "★",
    '&straightepsilon;'=> "ϵ",
    '&straightphi;'=> "ϕ",
    '&strns;'=> "¯",
  },
  '&su' => {
    '&sub;'=> "⊂",
    '&subdot;'=> "⪽",
    '&subE;'=> "⫅",
    '&sube;'=> "⊆",
    '&subedot;'=> "⫃",
    '&submult;'=> "⫁",
    '&subnE;'=> "⫋",
    '&subne;'=> "⊊",
    '&subplus;'=> "⪿",
    '&subrarr;'=> "⥹",
    '&subset;'=> "⊂",
    '&subseteq;'=> "⊆",
    '&subseteqq;'=> "⫅",
    '&subsetneq;'=> "⊊",
    '&subsetneqq;'=> "⫋",
    '&subsim;'=> "⫇",
    '&subsub;'=> "⫕",
    '&subsup;'=> "⫓",
    '&succapprox;'=> "⪸",
    '&succ;'=> "≻",
    '&succcurlyeq;'=> "≽",
    '&succeq;'=> "⪰",
    '&succnapprox;'=> "⪺",
    '&succneqq;'=> "⪶",
    '&succnsim;'=> "⋩",
    '&succsim;'=> "≿",
    '&sum;'=> "∑",
    '&sung;'=> "♪",
    '&sup1;'=> "¹",
    '&sup1'=> "¹",
    '&sup2;'=> "²",
    '&sup2'=> "²",
    '&sup3;'=> "³",
    '&sup3'=> "³",
    '&sup;'=> "⊃",
    '&supdot;'=> "⪾",
    '&supdsub;'=> "⫘",
    '&supE;'=> "⫆",
    '&supe;'=> "⊇",
    '&supedot;'=> "⫄",
    '&suphsol;'=> "⟉",
    '&suphsub;'=> "⫗",
    '&suplarr;'=> "⥻",
    '&supmult;'=> "⫂",
    '&supnE;'=> "⫌",
    '&supne;'=> "⊋",
    '&supplus;'=> "⫀",
    '&supset;'=> "⊃",
    '&supseteq;'=> "⊇",
    '&supseteqq;'=> "⫆",
    '&supsetneq;'=> "⊋",
    '&supsetneqq;'=> "⫌",
    '&supsim;'=> "⫈",
    '&supsub;'=> "⫔",
    '&supsup;'=> "⫖",
  },
  '&Su' => {
    '&Sub;'=> "⋐",
    '&Subset;'=> "⋐",
    '&SubsetEqual;'=> "⊆",
    '&Succeeds;'=> "≻",
    '&SucceedsEqual;'=> "⪰",
    '&SucceedsSlantEqual;'=> "≽",
    '&SucceedsTilde;'=> "≿",
    '&SuchThat;'=> "∋",
    '&Sum;'=> "∑",
    '&Sup;'=> "⋑",
    '&Superset;'=> "⊃",
    '&SupersetEqual;'=> "⊇",
    '&Supset;'=> "⋑",
  },
  '&sw' => {
    '&swarhk;'=> "⤦",
    '&swarr;'=> "↙",
    '&swArr;'=> "⇙",
    '&swarrow;'=> "↙",
    '&swnwar;'=> "⤪",
  },
  '&sz' => {
    '&szlig;'=> "ß",
    '&szlig'=> "ß",
  },
  '&Ta' => {
    '&Tab;'=> "\t",
    '&Tau;'=> "Τ",
  },
  '&ta' => {
    '&target;'=> "⌖",
    '&tau;'=> "τ",
  },
  '&tb' => {
    '&tbrk;'=> "⎴",
  },
  '&Tc' => {
    '&Tcaron;'=> "Ť",
    '&Tcedil;'=> "Ţ",
    '&Tcy;'=> "Т",
  },
  '&tc' => {
    '&tcaron;'=> "ť",
    '&tcedil;'=> "ţ",
    '&tcy;'=> "т",
  },
  '&td' => {
    '&tdot;'=> "⃛",
  },
  '&te' => {
    '&telrec;'=> "⌕",
  },
  '&Tf' => {
    '&Tfr;'=> "𝔗",
  },
  '&tf' => {
    '&tfr;'=> "𝔱",
  },
  '&th' => {
    '&there4;'=> "∴",
    '&therefore;'=> "∴",
    '&theta;'=> "θ",
    '&thetasym;'=> "ϑ",
    '&thetav;'=> "ϑ",
    '&thickapprox;'=> "≈",
    '&thicksim;'=> "∼",
    '&thinsp;'=> " ",
    '&thkap;'=> "≈",
    '&thksim;'=> "∼",
    '&thorn;'=> "þ",
    '&thorn'=> "þ",
  },
  '&Th' => {
    '&Therefore;'=> "∴",
    '&Theta;'=> "Θ",
    '&ThickSpace;'=> "  ",
    '&ThinSpace;'=> " ",
  },
  '&TH' => {
    '&THORN;'=> "Þ",
    '&THORN'=> "Þ",
  },
  '&ti' => {
    '&tilde;'=> "˜",
    '&timesbar;'=> "⨱",
    '&timesb;'=> "⊠",
    '&times;'=> "×",
    '&times'=> "×",
    '&timesd;'=> "⨰",
    '&tint;'=> "∭",
  },
  '&Ti' => {
    '&Tilde;'=> "∼",
    '&TildeEqual;'=> "≃",
    '&TildeFullEqual;'=> "≅",
    '&TildeTilde;'=> "≈",
  },
  '&to' => {
    '&toea;'=> "⤨",
    '&topbot;'=> "⌶",
    '&topcir;'=> "⫱",
    '&top;'=> "⊤",
    '&topf;'=> "𝕥",
    '&topfork;'=> "⫚",
    '&tosa;'=> "⤩",
  },
  '&To' => {
    '&Topf;'=> "𝕋",
  },
  '&tp' => {
    '&tprime;'=> "‴",
  },
  '&tr' => {
    '&trade;'=> "™",
    '&triangle;'=> "▵",
    '&triangledown;'=> "▿",
    '&triangleleft;'=> "◃",
    '&trianglelefteq;'=> "⊴",
    '&triangleq;'=> "≜",
    '&triangleright;'=> "▹",
    '&trianglerighteq;'=> "⊵",
    '&tridot;'=> "◬",
    '&trie;'=> "≜",
    '&triminus;'=> "⨺",
    '&triplus;'=> "⨹",
    '&trisb;'=> "⧍",
    '&tritime;'=> "⨻",
    '&trpezium;'=> "⏢",
  },
  '&TR' => {
    '&TRADE;'=> "™",
  },
  '&Tr' => {
    '&TripleDot;'=> "⃛",
  },
  '&Ts' => {
    '&Tscr;'=> "𝒯",
    '&Tstrok;'=> "Ŧ",
  },
  '&ts' => {
    '&tscr;'=> "𝓉",
    '&tscy;'=> "ц",
    '&tshcy;'=> "ћ",
    '&tstrok;'=> "ŧ",
  },
  '&TS' => {
    '&TScy;'=> "Ц",
    '&TSHcy;'=> "Ћ",
  },
  '&tw' => {
    '&twixt;'=> "≬",
    '&twoheadleftarrow;'=> "↞",
    '&twoheadrightarrow;'=> "↠",
  },
  '&Ua' => {
    '&Uacute;'=> "Ú",
    '&Uacute'=> "Ú",
    '&Uarr;'=> "↟",
    '&Uarrocir;'=> "⥉",
  },
  '&ua' => {
    '&uacute;'=> "ú",
    '&uacute'=> "ú",
    '&uarr;'=> "↑",
  },
  '&uA' => {
    '&uArr;'=> "⇑",
  },
  '&Ub' => {
    '&Ubrcy;'=> "Ў",
    '&Ubreve;'=> "Ŭ",
  },
  '&ub' => {
    '&ubrcy;'=> "ў",
    '&ubreve;'=> "ŭ",
  },
  '&Uc' => {
    '&Ucirc;'=> "Û",
    '&Ucirc'=> "Û",
    '&Ucy;'=> "У",
  },
  '&uc' => {
    '&ucirc;'=> "û",
    '&ucirc'=> "û",
    '&ucy;'=> "у",
  },
  '&ud' => {
    '&udarr;'=> "⇅",
    '&udblac;'=> "ű",
    '&udhar;'=> "⥮",
  },
  '&Ud' => {
    '&Udblac;'=> "Ű",
  },
  '&uf' => {
    '&ufisht;'=> "⥾",
    '&ufr;'=> "𝔲",
  },
  '&Uf' => {
    '&Ufr;'=> "𝔘",
  },
  '&Ug' => {
    '&Ugrave;'=> "Ù",
    '&Ugrave'=> "Ù",
  },
  '&ug' => {
    '&ugrave;'=> "ù",
    '&ugrave'=> "ù",
  },
  '&uH' => {
    '&uHar;'=> "⥣",
  },
  '&uh' => {
    '&uharl;'=> "↿",
    '&uharr;'=> "↾",
    '&uhblk;'=> "▀",
  },
  '&ul' => {
    '&ulcorn;'=> "⌜",
    '&ulcorner;'=> "⌜",
    '&ulcrop;'=> "⌏",
    '&ultri;'=> "◸",
  },
  '&Um' => {
    '&Umacr;'=> "Ū",
  },
  '&um' => {
    '&umacr;'=> "ū",
    '&uml;'=> "¨",
    '&uml'=> "¨",
  },
  '&Un' => {
    '&UnderBar;'=> "_",
    '&UnderBrace;'=> "⏟",
    '&UnderBracket;'=> "⎵",
    '&UnderParenthesis;'=> "⏝",
    '&Union;'=> "⋃",
    '&UnionPlus;'=> "⊎",
  },
  '&Uo' => {
    '&Uogon;'=> "Ų",
    '&Uopf;'=> "𝕌",
  },
  '&uo' => {
    '&uogon;'=> "ų",
    '&uopf;'=> "𝕦",
  },
  '&Up' => {
    '&UpArrowBar;'=> "⤒",
    '&UpArrow;'=> "↑",
    '&Uparrow;'=> "⇑",
    '&UpArrowDownArrow;'=> "⇅",
    '&UpDownArrow;'=> "↕",
    '&Updownarrow;'=> "⇕",
    '&UpEquilibrium;'=> "⥮",
    '&UpperLeftArrow;'=> "↖",
    '&UpperRightArrow;'=> "↗",
    '&Upsi;'=> "ϒ",
    '&Upsilon;'=> "Υ",
    '&UpTeeArrow;'=> "↥",
    '&UpTee;'=> "⊥",
  },
  '&up' => {
    '&uparrow;'=> "↑",
    '&updownarrow;'=> "↕",
    '&upharpoonleft;'=> "↿",
    '&upharpoonright;'=> "↾",
    '&uplus;'=> "⊎",
    '&upsi;'=> "υ",
    '&upsih;'=> "ϒ",
    '&upsilon;'=> "υ",
    '&upuparrows;'=> "⇈",
  },
  '&ur' => {
    '&urcorn;'=> "⌝",
    '&urcorner;'=> "⌝",
    '&urcrop;'=> "⌎",
    '&uring;'=> "ů",
    '&urtri;'=> "◹",
  },
  '&Ur' => {
    '&Uring;'=> "Ů",
  },
  '&Us' => {
    '&Uscr;'=> "𝒰",
  },
  '&us' => {
    '&uscr;'=> "𝓊",
  },
  '&ut' => {
    '&utdot;'=> "⋰",
    '&utilde;'=> "ũ",
    '&utri;'=> "▵",
    '&utrif;'=> "▴",
  },
  '&Ut' => {
    '&Utilde;'=> "Ũ",
  },
  '&uu' => {
    '&uuarr;'=> "⇈",
    '&uuml;'=> "ü",
    '&uuml'=> "ü",
  },
  '&Uu' => {
    '&Uuml;'=> "Ü",
    '&Uuml'=> "Ü",
  },
  '&uw' => {
    '&uwangle;'=> "⦧",
  },
  '&va' => {
    '&vangrt;'=> "⦜",
    '&varepsilon;'=> "ϵ",
    '&varkappa;'=> "ϰ",
    '&varnothing;'=> "∅",
    '&varphi;'=> "ϕ",
    '&varpi;'=> "ϖ",
    '&varpropto;'=> "∝",
    '&varr;'=> "↕",
    '&varrho;'=> "ϱ",
    '&varsigma;'=> "ς",
    '&varsubsetneq;'=> "⊊︀",
    '&varsubsetneqq;'=> "⫋︀",
    '&varsupsetneq;'=> "⊋︀",
    '&varsupsetneqq;'=> "⫌︀",
    '&vartheta;'=> "ϑ",
    '&vartriangleleft;'=> "⊲",
    '&vartriangleright;'=> "⊳",
  },
  '&vA' => {
    '&vArr;'=> "⇕",
  },
  '&vB' => {
    '&vBar;'=> "⫨",
    '&vBarv;'=> "⫩",
  },
  '&Vb' => {
    '&Vbar;'=> "⫫",
  },
  '&Vc' => {
    '&Vcy;'=> "В",
  },
  '&vc' => {
    '&vcy;'=> "в",
  },
  '&vd' => {
    '&vdash;'=> "⊢",
  },
  '&vD' => {
    '&vDash;'=> "⊨",
  },
  '&Vd' => {
    '&Vdash;'=> "⊩",
    '&Vdashl;'=> "⫦",
  },
  '&VD' => {
    '&VDash;'=> "⊫",
  },
  '&ve' => {
    '&veebar;'=> "⊻",
    '&vee;'=> "∨",
    '&veeeq;'=> "≚",
    '&vellip;'=> "⋮",
    '&verbar;'=> "|",
    '&vert;'=> "|",
  },
  '&Ve' => {
    '&Vee;'=> "⋁",
    '&Verbar;'=> "‖",
    '&Vert;'=> "‖",
    '&VerticalBar;'=> "∣",
    '&VerticalLine;'=> "|",
    '&VerticalSeparator;'=> "❘",
    '&VerticalTilde;'=> "≀",
    '&VeryThinSpace;'=> " ",
  },
  '&Vf' => {
    '&Vfr;'=> "𝔙",
  },
  '&vf' => {
    '&vfr;'=> "𝔳",
  },
  '&vl' => {
    '&vltri;'=> "⊲",
  },
  '&vn' => {
    '&vnsub;'=> "⊂⃒",
    '&vnsup;'=> "⊃⃒",
  },
  '&Vo' => {
    '&Vopf;'=> "𝕍",
  },
  '&vo' => {
    '&vopf;'=> "𝕧",
  },
  '&vp' => {
    '&vprop;'=> "∝",
  },
  '&vr' => {
    '&vrtri;'=> "⊳",
  },
  '&Vs' => {
    '&Vscr;'=> "𝒱",
  },
  '&vs' => {
    '&vscr;'=> "𝓋",
    '&vsubnE;'=> "⫋︀",
    '&vsubne;'=> "⊊︀",
    '&vsupnE;'=> "⫌︀",
    '&vsupne;'=> "⊋︀",
  },
  '&Vv' => {
    '&Vvdash;'=> "⊪",
  },
  '&vz' => {
    '&vzigzag;'=> "⦚",
  },
  '&Wc' => {
    '&Wcirc;'=> "Ŵ",
  },
  '&wc' => {
    '&wcirc;'=> "ŵ",
  },
  '&we' => {
    '&wedbar;'=> "⩟",
    '&wedge;'=> "∧",
    '&wedgeq;'=> "≙",
    '&weierp;'=> "℘",
  },
  '&We' => {
    '&Wedge;'=> "⋀",
  },
  '&Wf' => {
    '&Wfr;'=> "𝔚",
  },
  '&wf' => {
    '&wfr;'=> "𝔴",
  },
  '&Wo' => {
    '&Wopf;'=> "𝕎",
  },
  '&wo' => {
    '&wopf;'=> "𝕨",
  },
  '&wp' => {
    '&wp;'=> "℘",
  },
  '&wr' => {
    '&wr;'=> "≀",
    '&wreath;'=> "≀",
  },
  '&Ws' => {
    '&Wscr;'=> "𝒲",
  },
  '&ws' => {
    '&wscr;'=> "𝓌",
  },
  '&xc' => {
    '&xcap;'=> "⋂",
    '&xcirc;'=> "◯",
    '&xcup;'=> "⋃",
  },
  '&xd' => {
    '&xdtri;'=> "▽",
  },
  '&Xf' => {
    '&Xfr;'=> "𝔛",
  },
  '&xf' => {
    '&xfr;'=> "𝔵",
  },
  '&xh' => {
    '&xharr;'=> "⟷",
    '&xhArr;'=> "⟺",
  },
  '&Xi' => {
    '&Xi;'=> "Ξ",
  },
  '&xi' => {
    '&xi;'=> "ξ",
  },
  '&xl' => {
    '&xlarr;'=> "⟵",
    '&xlArr;'=> "⟸",
  },
  '&xm' => {
    '&xmap;'=> "⟼",
  },
  '&xn' => {
    '&xnis;'=> "⋻",
  },
  '&xo' => {
    '&xodot;'=> "⨀",
    '&xopf;'=> "𝕩",
    '&xoplus;'=> "⨁",
    '&xotime;'=> "⨂",
  },
  '&Xo' => {
    '&Xopf;'=> "𝕏",
  },
  '&xr' => {
    '&xrarr;'=> "⟶",
    '&xrArr;'=> "⟹",
  },
  '&Xs' => {
    '&Xscr;'=> "𝒳",
  },
  '&xs' => {
    '&xscr;'=> "𝓍",
    '&xsqcup;'=> "⨆",
  },
  '&xu' => {
    '&xuplus;'=> "⨄",
    '&xutri;'=> "△",
  },
  '&xv' => {
    '&xvee;'=> "⋁",
  },
  '&xw' => {
    '&xwedge;'=> "⋀",
  },
  '&Ya' => {
    '&Yacute;'=> "Ý",
    '&Yacute'=> "Ý",
  },
  '&ya' => {
    '&yacute;'=> "ý",
    '&yacute'=> "ý",
    '&yacy;'=> "я",
  },
  '&YA' => {
    '&YAcy;'=> "Я",
  },
  '&Yc' => {
    '&Ycirc;'=> "Ŷ",
    '&Ycy;'=> "Ы",
  },
  '&yc' => {
    '&ycirc;'=> "ŷ",
    '&ycy;'=> "ы",
  },
  '&ye' => {
    '&yen;'=> "¥",
    '&yen'=> "¥",
  },
  '&Yf' => {
    '&Yfr;'=> "𝔜",
  },
  '&yf' => {
    '&yfr;'=> "𝔶",
  },
  '&YI' => {
    '&YIcy;'=> "Ї",
  },
  '&yi' => {
    '&yicy;'=> "ї",
  },
  '&Yo' => {
    '&Yopf;'=> "𝕐",
  },
  '&yo' => {
    '&yopf;'=> "𝕪",
  },
  '&Ys' => {
    '&Yscr;'=> "𝒴",
  },
  '&ys' => {
    '&yscr;'=> "𝓎",
  },
  '&YU' => {
    '&YUcy;'=> "Ю",
  },
  '&yu' => {
    '&yucy;'=> "ю",
    '&yuml;'=> "ÿ",
    '&yuml'=> "ÿ",
  },
  '&Yu' => {
    '&Yuml;'=> "Ÿ",
  },
  '&Za' => {
    '&Zacute;'=> "Ź",
  },
  '&za' => {
    '&zacute;'=> "ź",
  },
  '&Zc' => {
    '&Zcaron;'=> "Ž",
    '&Zcy;'=> "З",
  },
  '&zc' => {
    '&zcaron;'=> "ž",
    '&zcy;'=> "з",
  },
  '&Zd' => {
    '&Zdot;'=> "Ż",
  },
  '&zd' => {
    '&zdot;'=> "ż",
  },
  '&ze' => {
    '&zeetrf;'=> "ℨ",
    '&zeta;'=> "ζ",
  },
  '&Ze' => {
    '&ZeroWidthSpace;'=> "​",
    '&Zeta;'=> "Ζ",
  },
  '&zf' => {
    '&zfr;'=> "𝔷",
  },
  '&Zf' => {
    '&Zfr;'=> "ℨ",
  },
  '&ZH' => {
    '&ZHcy;'=> "Ж",
  },
  '&zh' => {
    '&zhcy;'=> "ж",
  },
  '&zi' => {
    '&zigrarr;'=> "⇝",
  },
  '&zo' => {
    '&zopf;'=> "𝕫",
  },
  '&Zo' => {
    '&Zopf;'=> "ℤ",
  },
  '&Zs' => {
    '&Zscr;'=> "𝒵",
  },
  '&zs' => {
    '&zscr;'=> "𝓏",
  },
  '&zw' => {
    '&zwj;'=> "‍",
    '&zwnj;'=> "‌",
  },
