#!/usr/bin/env bash

su www-data <<EOSU

/var/www/html/bin/magento sampledata:deploy;
/var/www/html/bin/magento setup:upgrade;
/var/www/html/bin/magento setup:di:compile;
/var/www/html/bin/magento config:set sales/gift_options/allow_order true;
/var/www/html/bin/magento config:set sales/gift_options/allow_items true;
/var/www/html/bin/magento config:set payment/banktransfer/active 1;
/var/www/html/bin/magento config:set payment/checkmo/active 1;
/var/www/html/bin/magento config:set customer/create_account/confirm true;
/var/www/html/bin/magento config:set customer/password/max_number_password_reset_requests 0;
/var/www/html/bin/magento config:set customer/password/min_time_between_password_reset_requests 0;
/var/www/html/bin/magento config:set customer/password/max_number_password_reset_requests 0;
/var/www/html/bin/magento config:set customer/password/min_time_between_password_reset_requests 0;

EOSU
