use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 

class CSS::Module::CSS3::Fonts::AtFontFace::Spec::Actions {
    method family-name($/) { make $.rule($/) }
    method font-face-name($/) { make $.rule($/) }
}
