=head1 URI::Encode

A Perl 6 module for encoding / decoding URIs

=head1 Synopsis

    use URI::Encode;

    # for encoding whole URIs, ignores reserved chars: #$&+,/:;=?@
    my $encoded_uri = uri_encode('http://www.example.com/?name=john doe&age=54');

    # encode every reserved char
    my $encoded_uri_component = uri_encode_component('some text/to encode+ safely');

    # remove percent encoding
    my $decoded_uri = uri_decode(http://www.example.com/?name=john%20doe&age=54');

    # provided for symmetry, is the same as uri_decode()
    my $decoded_component = uri_decode_component('some%20text%2Fto%20%2B%20safely');

=head1 Author

David Farrell E<copy> 2015

=head1 License

FreeBSD - see LICENSE

=cut
