use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 
role CSS::Module::CSS3::Fonts::Spec::Interface {
    method absolute-size($/) { ... }
    method annotation($/) { ... }
    method character-variant($/) { ... }
    method common-lig-values($/) { ... }
    method contextual-alt-values($/) { ... }
    method discretionary-lig-values($/) { ... }
    method east-asian-variant-values($/) { ... }
    method east-asian-width-values($/) { ... }
    method family-name($/) { ... }
    method feature-tag-value($/) { ... }
    method feature-value-name($/) { ... }
    method font-variant-css21($/) { ... }
    method generic-family($/) { ... }
    method historical-lig-values($/) { ... }
    method identifiers($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method numeric-figure-values($/) { ... }
    method numeric-fraction-values($/) { ... }
    method numeric-spacing-values($/) { ... }
    method ornaments($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method string($/) { ... }
    method styleset($/) { ... }
    method stylistic($/) { ... }
    method swash($/) { ... }
}
