Minecraft-Tools
===============

Some Perl 6 modules to allow you to do admin-related things with that one game.
Does not yet include a playable client, sorry.

Contents
--------
`Net::Minecraft::Query`::
A class that can read server stats using the GS4 query protocol (players online,
mods loaded etc). Might actually work on other servers besides Minecraft, but I
don't have any of those to try.

`Net::Minecraft::Rcon`::
Rcon client. http://wiki.vg/Rcon[The reverse engineering wiki] has the *best*
description of what this is. With the recent addition of world-manipulation
commands like `setblock` and `fill`, you can use this to make Minecraft an
interactive, crashy canvas.

`Net::Minecraft::Version:<2+>`::
Utility functions to grab the remote version list,
convert a version string into a downloadable URL for your server,
and safely round-trip version strings to/from Perl 6 `Version` objects.
Comes with a wrapper script, `bin/minecraft-versioncheck`.

`Net::Minecraft::Version:<1.*>`::
Original version of the above module, which I wrote before finding out they
*had* a remote list. Kept here to give module installer authors a hard time.
