#!/usr/bin/env perl6
#
use v6;

# Running the pod file will create a pdf using wkhtmltopdf
#
my Str $pod = "$*PROGRAM";
my Str $pdf = $pod;
$pdf ~~ s/\. <-[.]>+ $/.pdf/;
shell( "perl6 --doc=HTML '$pod' | wkhtmltopdf - '$pdf'");

#-------------------------------------------------------------------------------

=begin pod

=begin Xhtml
<style>
  pre {
/**/
    border-width:       2px;
    border-style:       solid;
    border-color:       #060;
    padding:            10px 0 3px 10px;
    color:              #060;
    background-color:   #eaefea;
    font-family:        FreeMono;
  }
</style>
=end Xhtml

=TITLE class BSON::Binary

=SUBTITLE Container for binary data

  package BSON { class Binary { ... } }

Use as

=begin code

use UUID;
use BSON::Binary;

my UUID $uuid .= new(:version(4));
my BSON::Binary $bin .= new(
  :data($uuid.Blob),
  :type(BSON::C-UUID)
);

=end code

=head1 METHODS

=head2 method new

Defined as

  method new ( Buf :$data, Int :$type = BSON::C-GENERIC )

Store binary data in the object. The following codes are available:

=item C<C-GENERIC>. Generic binary data.
=item C<C-FUNCTION>. Encoding of function code.
=item C<C-UUID>. Encoding of UUID
=item C<C-MD5>. Encoding of MD5

=head2 method perl

Defined as

  method perl ( Int $indent = 0 --> Str )

Should be used like any other perl without the $indent set. Otherwise it starts
of indented.


=end pod
