use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 

class CSS::Module::CSS3::Fonts::Spec::Actions {
    method font-variant-css21($/) { make $.rule($/) }
    method expr-font-family($/) { make $.list($/) }
    method generic-family($/) { make $.rule($/) }
    method family-name($/) { make $.rule($/) }
    method expr-font-size($/) { make $.list($/) }
    method absolute-size($/) { make $.rule($/) }
    method relative-size($/) { make $.rule($/) }
    method expr-font-stretch($/) { make $.list($/) }
    method expr-font-style($/) { make $.list($/) }
    method expr-font-weight($/) { make $.list($/) }
    method expr-line-height($/) { make $.list($/) }
}
