.TH META6::To::Man 1 2017-09-21 Perl6.org
.SH NAME META6::To::Man
item - Produces a rudimentary man page from a Perl 6 META6.json (or META.json) file.
.SH SYNOPSIS
use META6::To::Man;
.SH DESCRIPTION
This module is in the Perl 6 ecosystem.
Its source can be found at
.UR https://github.com/tbrowder/META6-To-Man-Perl6.git
.UE .
.SH BUGS
Submit bug reports to
.UR https://github.com/tbrowder/META6-To-Man-Perl6/issues
.UE .
.SH LICENSE
Artistic-2.0
