use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 

class CSS::Module::CSS1::Spec::Actions {
    method expr-font-family($/) { make $.list($/) }
    method generic-family($/) { make $.rule($/) }
    method family-name($/) { make $.rule($/) }
    method expr-font-style($/) { make $.list($/) }
    method expr-font-variant($/) { make $.list($/) }
    method expr-font-weight($/) { make $.list($/) }
    method expr-font-size($/) { make $.list($/) }
    method absolute-size($/) { make $.rule($/) }
    method relative-size($/) { make $.rule($/) }
    method expr-background-color($/) { make $.list($/) }
    method expr-background-image($/) { make $.list($/) }
    method expr-background-repeat($/) { make $.list($/) }
    method expr-background-attachment($/) { make $.list($/) }
    method expr-background-position($/) { make $.list($/) }
    method expr-line-height($/) { make $.list($/) }
    method expr-border-top-width($/) { make $.list($/) }
    method expr-border-right-width($/) { make $.list($/) }
    method expr-border-bottom-width($/) { make $.list($/) }
    method expr-border-left-width($/) { make $.list($/) }
    method expr-border-width($/) { make $.list($/) }
    method expr-border-color($/) { make $.list($/) }
    method expr-border-style($/) { make $.list($/) }
    method expr-border-top-style($/) { make $.list($/) }
    method expr-border-right-style($/) { make $.list($/) }
    method expr-border-bottom-style($/) { make $.list($/) }
    method expr-border-left-style($/) { make $.list($/) }
    method expr-list-style-type($/) { make $.list($/) }
    method expr-list-style-image($/) { make $.list($/) }
    method expr-list-style-position($/) { make $.list($/) }
}
