use v6;
#  -- DO NOT EDIT --
# generated by: make-modules.pl 
role CSS::Module::CSS1::Spec::Interface {
    method absolute-size($/) { ... }
    method color($/) { ... }
    method family-name($/) { ... }
    method generic-family($/) { ... }
    method identifiers($/) { ... }
    method integer($/) { ... }
    method length($/) { ... }
    method number($/) { ... }
    method percentage($/) { ... }
    method relative-size($/) { ... }
    method string($/) { ... }
    method uri($/) { ... }
}
